/*
###############################################################
#  Generated by:      Cadence Innovus 20.10-p004_1
#  OS:                Linux x86_64(Host ID cad29)
#  Generated on:      Thu Mar 17 16:21:16 2022
#  Design:            CHIP
#  Command:           saveNetlist CHIP.v
###############################################################
*/
module alu_DW01_add_0 (
	A, 
	B, 
	CI, 
	SUM, 
	CO);
   input [8:0] A;
   input [8:0] B;
   input CI;
   output [8:0] SUM;
   output CO;

   // Internal wires
   wire n1;
   wire [8:1] carry;

   FA1S U1_7 (.S(SUM[7]),
	.CO(SUM[8]),
	.A(A[7]),
	.B(B[7]),
	.CI(carry[7]));
   FA1S U1_1 (.S(SUM[1]),
	.CO(carry[2]),
	.A(A[1]),
	.B(B[1]),
	.CI(n1));
   FA1S U1_2 (.S(SUM[2]),
	.CO(carry[3]),
	.A(A[2]),
	.B(B[2]),
	.CI(carry[2]));
   FA1S U1_3 (.S(SUM[3]),
	.CO(carry[4]),
	.A(A[3]),
	.B(B[3]),
	.CI(carry[3]));
   FA1S U1_4 (.S(SUM[4]),
	.CO(carry[5]),
	.A(A[4]),
	.B(B[4]),
	.CI(carry[4]));
   FA1S U1_5 (.S(SUM[5]),
	.CO(carry[6]),
	.A(A[5]),
	.B(B[5]),
	.CI(carry[5]));
   FA1S U1_6 (.S(SUM[6]),
	.CO(carry[7]),
	.A(A[6]),
	.B(B[6]),
	.CI(carry[6]));
   AN2 U1 (.O(n1),
	.I1(B[0]),
	.I2(A[0]));
endmodule

module alu_DW01_sub_0 (
	A, 
	B, 
	CI, 
	DIFF, 
	CO, 
	FE_DBTN5_out_inst_3_0, 
	FE_DBTN10_out_inst_3_5, 
	FE_DBTN11_out_inst_3_6, 
	FE_DBTN9_out_inst_3_4, 
	FE_DBTN6_out_inst_3_1, 
	FE_DBTN8_out_inst_3_3, 
	FE_DBTN7_out_inst_3_2);
   input [8:0] A;
   input [8:0] B;
   input CI;
   output [8:0] DIFF;
   output CO;
   input FE_DBTN5_out_inst_3_0;
   input FE_DBTN10_out_inst_3_5;
   input FE_DBTN11_out_inst_3_6;
   input FE_DBTN9_out_inst_3_4;
   input FE_DBTN6_out_inst_3_1;
   input FE_DBTN8_out_inst_3_3;
   input FE_DBTN7_out_inst_3_2;

   // Internal wires
   wire n1;
   wire n9;
   wire [9:0] carry;

   FA1S U2_1 (.S(DIFF[1]),
	.CO(carry[2]),
	.A(A[1]),
	.B(FE_DBTN5_out_inst_3_0),
	.CI(carry[1]));
   FA1S U2_2 (.S(DIFF[2]),
	.CO(carry[3]),
	.A(A[2]),
	.B(FE_DBTN6_out_inst_3_1),
	.CI(carry[2]));
   FA1S U2_3 (.S(DIFF[3]),
	.CO(carry[4]),
	.A(A[3]),
	.B(FE_DBTN7_out_inst_3_2),
	.CI(carry[3]));
   FA1S U2_4 (.S(DIFF[4]),
	.CO(carry[5]),
	.A(A[4]),
	.B(FE_DBTN8_out_inst_3_3),
	.CI(carry[4]));
   FA1S U2_5 (.S(DIFF[5]),
	.CO(carry[6]),
	.A(A[5]),
	.B(FE_DBTN9_out_inst_3_4),
	.CI(carry[5]));
   FA1S U2_6 (.S(DIFF[6]),
	.CO(carry[7]),
	.A(A[6]),
	.B(FE_DBTN10_out_inst_3_5),
	.CI(carry[6]));
   FA1S U2_7 (.S(DIFF[7]),
	.CO(carry[8]),
	.A(A[7]),
	.B(FE_DBTN11_out_inst_3_6),
	.CI(carry[7]));
   INV1S U2 (.O(n9),
	.I(B[0]));
   INV1S U9 (.O(n1),
	.I(A[0]));
   XNR2HS U10 (.O(DIFF[0]),
	.I1(n9),
	.I2(A[0]));
   ND2 U11 (.O(carry[1]),
	.I1(B[0]),
	.I2(n1));
   INV1S U12 (.O(DIFF[8]),
	.I(carry[8]));
endmodule

module alu_DW_mult_uns_0 (
	a, 
	b, 
	product);
   input [7:0] a;
   input [7:0] b;
   output [15:0] product;

   // Internal wires
   wire FE_OFN67_n247;
   wire FE_OFN66_n243;
   wire FE_OFN13_FE_DBTN5_out_inst_3_0;
   wire FE_OFN12_FE_DBTN6_out_inst_3_1;
   wire FE_OFN11_FE_DBTN7_out_inst_3_2;
   wire FE_OFN10_FE_DBTN8_out_inst_3_3;
   wire FE_OFN9_FE_DBTN9_out_inst_3_4;
   wire FE_OFN8_FE_DBTN10_out_inst_3_5;
   wire FE_OFN7_FE_DBTN11_out_inst_3_6;
   wire FE_OFN6_FE_DBTN12_reg_data_b_1;
   wire FE_OFN5_FE_DBTN13_reg_data_b_2;
   wire FE_OFN4_FE_DBTN14_reg_data_b_3;
   wire FE_OFN3_FE_DBTN15_reg_data_b_4;
   wire FE_OFN2_FE_DBTN16_reg_data_b_5;
   wire FE_OFN1_FE_DBTN17_reg_data_b_6;
   wire FE_OFN0_FE_DBTN18_reg_data_b_7;
   wire n2;
   wire n3;
   wire n4;
   wire n5;
   wire n6;
   wire n7;
   wire n8;
   wire n9;
   wire n10;
   wire n11;
   wire n12;
   wire n13;
   wire n14;
   wire n15;
   wire n16;
   wire n17;
   wire n18;
   wire n19;
   wire n20;
   wire n21;
   wire n22;
   wire n23;
   wire n24;
   wire n25;
   wire n26;
   wire n27;
   wire n28;
   wire n29;
   wire n30;
   wire n31;
   wire n32;
   wire n33;
   wire n34;
   wire n35;
   wire n36;
   wire n37;
   wire n38;
   wire n39;
   wire n40;
   wire n41;
   wire n42;
   wire n43;
   wire n44;
   wire n45;
   wire n46;
   wire n47;
   wire n48;
   wire n49;
   wire n50;
   wire n51;
   wire n52;
   wire n53;
   wire n54;
   wire n55;
   wire n56;
   wire n57;
   wire n58;
   wire n59;
   wire n60;
   wire n61;
   wire n62;
   wire n63;
   wire n64;
   wire n65;
   wire n66;
   wire n67;
   wire n68;
   wire n69;
   wire n70;
   wire n71;
   wire n72;
   wire n73;
   wire n74;
   wire n75;
   wire n76;
   wire n77;
   wire n78;
   wire n79;
   wire n80;
   wire n81;
   wire n82;
   wire n83;
   wire n84;
   wire n85;
   wire n86;
   wire n87;
   wire n88;
   wire n89;
   wire n90;
   wire n91;
   wire n92;
   wire n93;
   wire n94;
   wire n95;
   wire n96;
   wire n97;
   wire n98;
   wire n99;
   wire n100;
   wire n101;
   wire n102;
   wire n103;
   wire n104;
   wire n105;
   wire n106;
   wire n107;
   wire n108;
   wire n109;
   wire n110;
   wire n111;
   wire n112;
   wire n113;
   wire n114;
   wire n115;
   wire n116;
   wire n117;
   wire n118;
   wire n119;
   wire n120;
   wire n121;
   wire n122;
   wire n123;
   wire n124;
   wire n125;
   wire n126;
   wire n127;
   wire n128;
   wire n129;
   wire n130;
   wire n131;
   wire n132;
   wire n133;
   wire n134;
   wire n135;
   wire n136;
   wire n137;
   wire n138;
   wire n139;
   wire n140;
   wire n141;
   wire n142;
   wire n143;
   wire n144;
   wire n145;
   wire n146;
   wire n147;
   wire n148;
   wire n149;
   wire n150;
   wire n151;
   wire n152;
   wire n153;
   wire n154;
   wire n155;
   wire n156;
   wire n157;
   wire n158;
   wire n159;
   wire n160;
   wire n161;
   wire n243;
   wire n247;

   BUF1S FE_OFC67_n247 (.O(FE_OFN67_n247),
	.I(n247));
   BUF1S FE_OFC66_n243 (.O(FE_OFN66_n243),
	.I(n243));
   BUF1S FE_OFC13_FE_DBTN5_out_inst_3_0 (.O(FE_OFN13_FE_DBTN5_out_inst_3_0),
	.I(a[1]));
   BUF1S FE_OFC12_FE_DBTN6_out_inst_3_1 (.O(FE_OFN12_FE_DBTN6_out_inst_3_1),
	.I(a[2]));
   BUF1S FE_OFC11_FE_DBTN7_out_inst_3_2 (.O(FE_OFN11_FE_DBTN7_out_inst_3_2),
	.I(a[3]));
   BUF1S FE_OFC10_FE_DBTN8_out_inst_3_3 (.O(FE_OFN10_FE_DBTN8_out_inst_3_3),
	.I(a[4]));
   BUF1S FE_OFC9_FE_DBTN9_out_inst_3_4 (.O(FE_OFN9_FE_DBTN9_out_inst_3_4),
	.I(a[5]));
   BUF1S FE_OFC8_FE_DBTN10_out_inst_3_5 (.O(FE_OFN8_FE_DBTN10_out_inst_3_5),
	.I(a[6]));
   BUF1S FE_OFC7_FE_DBTN11_out_inst_3_6 (.O(FE_OFN7_FE_DBTN11_out_inst_3_6),
	.I(a[7]));
   BUF1S FE_OFC6_FE_DBTN12_reg_data_b_1 (.O(FE_OFN6_FE_DBTN12_reg_data_b_1),
	.I(b[1]));
   BUF1S FE_OFC5_FE_DBTN13_reg_data_b_2 (.O(FE_OFN5_FE_DBTN13_reg_data_b_2),
	.I(b[2]));
   BUF1S FE_OFC4_FE_DBTN14_reg_data_b_3 (.O(FE_OFN4_FE_DBTN14_reg_data_b_3),
	.I(b[3]));
   BUF1S FE_OFC3_FE_DBTN15_reg_data_b_4 (.O(FE_OFN3_FE_DBTN15_reg_data_b_4),
	.I(b[4]));
   BUF1S FE_OFC2_FE_DBTN16_reg_data_b_5 (.O(FE_OFN2_FE_DBTN16_reg_data_b_5),
	.I(b[5]));
   BUF1S FE_OFC1_FE_DBTN17_reg_data_b_6 (.O(FE_OFN1_FE_DBTN17_reg_data_b_6),
	.I(b[6]));
   BUF1S FE_OFC0_FE_DBTN18_reg_data_b_7 (.O(FE_OFN0_FE_DBTN18_reg_data_b_7),
	.I(b[7]));
   FA1S U2 (.S(product[14]),
	.CO(product[15]),
	.A(n99),
	.B(n15),
	.CI(n2));
   FA1S U3 (.S(product[13]),
	.CO(n2),
	.A(n16),
	.B(n17),
	.CI(n3));
   FA1S U4 (.S(product[12]),
	.CO(n3),
	.A(n18),
	.B(n21),
	.CI(n4));
   FA1S U5 (.S(product[11]),
	.CO(n4),
	.A(n27),
	.B(n22),
	.CI(n5));
   FA1S U6 (.S(product[10]),
	.CO(n5),
	.A(n35),
	.B(n28),
	.CI(n6));
   FA1S U7 (.S(product[9]),
	.CO(n6),
	.A(n45),
	.B(n36),
	.CI(n7));
   FA1S U8 (.S(product[8]),
	.CO(n7),
	.A(n57),
	.B(n46),
	.CI(n8));
   FA1S U9 (.S(product[7]),
	.CO(n8),
	.A(n69),
	.B(n58),
	.CI(n9));
   FA1S U10 (.S(product[6]),
	.CO(n9),
	.A(n79),
	.B(n70),
	.CI(n10));
   FA1S U11 (.S(product[5]),
	.CO(n10),
	.A(n87),
	.B(n80),
	.CI(n11));
   FA1S U12 (.S(product[4]),
	.CO(n11),
	.A(n93),
	.B(n88),
	.CI(n12));
   FA1S U13 (.S(product[3]),
	.CO(n12),
	.A(n96),
	.B(n13),
	.CI(n94));
   FA1S U14 (.S(product[2]),
	.CO(n13),
	.A(n146),
	.B(n14),
	.CI(n98));
   HA1 U15 (.S(product[1]),
	.C(n14),
	.A(n154),
	.B(n161));
   FA1S U16 (.S(n16),
	.CO(n15),
	.A(n107),
	.B(n100),
	.CI(n19));
   FA1S U17 (.S(n18),
	.CO(n17),
	.A(n25),
	.B(n20),
	.CI(n23));
   FA1S U18 (.S(n20),
	.CO(n19),
	.A(n115),
	.B(n101),
	.CI(n108));
   FA1S U19 (.S(n22),
	.CO(n21),
	.A(n31),
	.B(n24),
	.CI(n29));
   FA1S U20 (.S(n24),
	.CO(n23),
	.A(n116),
	.B(n33),
	.CI(n26));
   FA1S U21 (.S(n26),
	.CO(n25),
	.A(n123),
	.B(n102),
	.CI(n109));
   FA1S U22 (.S(n28),
	.CO(n27),
	.A(n32),
	.B(n37),
	.CI(n30));
   FA1S U23 (.S(n30),
	.CO(n29),
	.A(n41),
	.B(n34),
	.CI(n39));
   FA1S U24 (.S(n32),
	.CO(n31),
	.A(n124),
	.B(n117),
	.CI(n43));
   FA1S U25 (.S(n34),
	.CO(n33),
	.A(n131),
	.B(n103),
	.CI(n110));
   FA1S U26 (.S(n36),
	.CO(n35),
	.A(n40),
	.B(n47),
	.CI(n38));
   FA1S U27 (.S(n38),
	.CO(n37),
	.A(n44),
	.B(n51),
	.CI(n49));
   FA1S U28 (.S(n40),
	.CO(n39),
	.A(n55),
	.B(n53),
	.CI(n42));
   FA1S U29 (.S(n42),
	.CO(n41),
	.A(n118),
	.B(n125),
	.CI(n132));
   FA1S U30 (.S(n44),
	.CO(n43),
	.A(n139),
	.B(n104),
	.CI(n111));
   FA1S U31 (.S(n46),
	.CO(n45),
	.A(n50),
	.B(n59),
	.CI(n48));
   FA1S U32 (.S(n48),
	.CO(n47),
	.A(n54),
	.B(n52),
	.CI(n61));
   FA1S U33 (.S(n50),
	.CO(n49),
	.A(n56),
	.B(n65),
	.CI(n63));
   FA1S U34 (.S(n52),
	.CO(n51),
	.A(n140),
	.B(n133),
	.CI(n67));
   FA1S U35 (.S(n54),
	.CO(n53),
	.A(n126),
	.B(n119),
	.CI(n147));
   HA1 U36 (.S(n56),
	.C(n55),
	.A(n112),
	.B(n105));
   FA1S U37 (.S(n58),
	.CO(n57),
	.A(n71),
	.B(n62),
	.CI(n60));
   FA1S U38 (.S(n60),
	.CO(n59),
	.A(n64),
	.B(n66),
	.CI(n73));
   FA1S U39 (.S(n62),
	.CO(n61),
	.A(n77),
	.B(n68),
	.CI(n75));
   FA1S U40 (.S(n64),
	.CO(n63),
	.A(n141),
	.B(n127),
	.CI(n134));
   FA1S U41 (.S(n66),
	.CO(n65),
	.A(n155),
	.B(n120),
	.CI(n148));
   HA1 U42 (.S(n68),
	.C(n67),
	.A(n113),
	.B(n106));
   FA1S U43 (.S(n70),
	.CO(n69),
	.A(n81),
	.B(n74),
	.CI(n72));
   FA1S U44 (.S(n72),
	.CO(n71),
	.A(n78),
	.B(n83),
	.CI(n76));
   FA1S U45 (.S(n74),
	.CO(n73),
	.A(n142),
	.B(n135),
	.CI(n85));
   FA1S U46 (.S(n76),
	.CO(n75),
	.A(n156),
	.B(n128),
	.CI(n149));
   HA1 U47 (.S(n78),
	.C(n77),
	.A(n121),
	.B(n114));
   FA1S U48 (.S(n80),
	.CO(n79),
	.A(n89),
	.B(n84),
	.CI(n82));
   FA1S U49 (.S(n82),
	.CO(n81),
	.A(n150),
	.B(n91),
	.CI(n86));
   FA1S U50 (.S(n84),
	.CO(n83),
	.A(n157),
	.B(n136),
	.CI(n143));
   HA1 U51 (.S(n86),
	.C(n85),
	.A(n129),
	.B(n122));
   FA1S U52 (.S(n88),
	.CO(n87),
	.A(n95),
	.B(n92),
	.CI(n90));
   FA1S U53 (.S(n90),
	.CO(n89),
	.A(n158),
	.B(n144),
	.CI(n151));
   HA1 U54 (.S(n92),
	.C(n91),
	.A(n137),
	.B(n130));
   FA1S U55 (.S(n94),
	.CO(n93),
	.A(n159),
	.B(n152),
	.CI(n97));
   HA1 U56 (.S(n96),
	.C(n95),
	.A(n145),
	.B(n138));
   HA1 U57 (.S(n98),
	.C(n97),
	.A(n160),
	.B(n153));
   INV1S U169 (.O(n247),
	.I(a[0]));
   INV1S U170 (.O(n243),
	.I(b[0]));
   NR2 U174 (.O(product[0]),
	.I1(n247),
	.I2(n243));
   NR2 U175 (.O(n99),
	.I1(a[7]),
	.I2(b[7]));
   NR2 U176 (.O(n161),
	.I1(n247),
	.I2(b[1]));
   NR2 U177 (.O(n160),
	.I1(FE_OFN67_n247),
	.I2(b[2]));
   NR2 U178 (.O(n159),
	.I1(FE_OFN67_n247),
	.I2(FE_OFN4_FE_DBTN14_reg_data_b_3));
   NR2 U179 (.O(n158),
	.I1(FE_OFN67_n247),
	.I2(b[4]));
   NR2 U180 (.O(n157),
	.I1(FE_OFN67_n247),
	.I2(b[5]));
   NR2 U181 (.O(n156),
	.I1(FE_OFN67_n247),
	.I2(FE_OFN1_FE_DBTN17_reg_data_b_6));
   NR2 U182 (.O(n155),
	.I1(FE_OFN67_n247),
	.I2(FE_OFN0_FE_DBTN18_reg_data_b_7));
   NR2 U183 (.O(n154),
	.I1(n243),
	.I2(a[1]));
   NR2 U184 (.O(n153),
	.I1(b[1]),
	.I2(a[1]));
   NR2 U185 (.O(n152),
	.I1(b[2]),
	.I2(a[1]));
   NR2 U186 (.O(n151),
	.I1(FE_OFN4_FE_DBTN14_reg_data_b_3),
	.I2(a[1]));
   NR2 U187 (.O(n150),
	.I1(b[4]),
	.I2(FE_OFN13_FE_DBTN5_out_inst_3_0));
   NR2 U188 (.O(n149),
	.I1(b[5]),
	.I2(FE_OFN13_FE_DBTN5_out_inst_3_0));
   NR2 U189 (.O(n148),
	.I1(FE_OFN1_FE_DBTN17_reg_data_b_6),
	.I2(FE_OFN13_FE_DBTN5_out_inst_3_0));
   NR2 U190 (.O(n147),
	.I1(FE_OFN0_FE_DBTN18_reg_data_b_7),
	.I2(FE_OFN13_FE_DBTN5_out_inst_3_0));
   NR2 U191 (.O(n146),
	.I1(FE_OFN66_n243),
	.I2(FE_OFN12_FE_DBTN6_out_inst_3_1));
   NR2 U192 (.O(n145),
	.I1(FE_OFN6_FE_DBTN12_reg_data_b_1),
	.I2(FE_OFN12_FE_DBTN6_out_inst_3_1));
   NR2 U193 (.O(n144),
	.I1(FE_OFN5_FE_DBTN13_reg_data_b_2),
	.I2(FE_OFN12_FE_DBTN6_out_inst_3_1));
   NR2 U194 (.O(n143),
	.I1(FE_OFN4_FE_DBTN14_reg_data_b_3),
	.I2(FE_OFN12_FE_DBTN6_out_inst_3_1));
   NR2 U195 (.O(n142),
	.I1(b[4]),
	.I2(FE_OFN12_FE_DBTN6_out_inst_3_1));
   NR2 U196 (.O(n141),
	.I1(FE_OFN2_FE_DBTN16_reg_data_b_5),
	.I2(a[2]));
   NR2 U197 (.O(n140),
	.I1(FE_OFN1_FE_DBTN17_reg_data_b_6),
	.I2(a[2]));
   NR2 U198 (.O(n139),
	.I1(FE_OFN0_FE_DBTN18_reg_data_b_7),
	.I2(a[2]));
   NR2 U199 (.O(n138),
	.I1(FE_OFN66_n243),
	.I2(FE_OFN11_FE_DBTN7_out_inst_3_2));
   NR2 U200 (.O(n137),
	.I1(FE_OFN6_FE_DBTN12_reg_data_b_1),
	.I2(FE_OFN11_FE_DBTN7_out_inst_3_2));
   NR2 U201 (.O(n136),
	.I1(FE_OFN5_FE_DBTN13_reg_data_b_2),
	.I2(FE_OFN11_FE_DBTN7_out_inst_3_2));
   NR2 U202 (.O(n135),
	.I1(FE_OFN4_FE_DBTN14_reg_data_b_3),
	.I2(FE_OFN11_FE_DBTN7_out_inst_3_2));
   NR2 U203 (.O(n134),
	.I1(FE_OFN3_FE_DBTN15_reg_data_b_4),
	.I2(a[3]));
   NR2 U204 (.O(n133),
	.I1(FE_OFN2_FE_DBTN16_reg_data_b_5),
	.I2(a[3]));
   NR2 U205 (.O(n132),
	.I1(FE_OFN1_FE_DBTN17_reg_data_b_6),
	.I2(a[3]));
   NR2 U206 (.O(n131),
	.I1(FE_OFN0_FE_DBTN18_reg_data_b_7),
	.I2(a[3]));
   NR2 U207 (.O(n130),
	.I1(FE_OFN66_n243),
	.I2(FE_OFN10_FE_DBTN8_out_inst_3_3));
   NR2 U208 (.O(n129),
	.I1(FE_OFN6_FE_DBTN12_reg_data_b_1),
	.I2(FE_OFN10_FE_DBTN8_out_inst_3_3));
   NR2 U209 (.O(n128),
	.I1(FE_OFN5_FE_DBTN13_reg_data_b_2),
	.I2(FE_OFN10_FE_DBTN8_out_inst_3_3));
   NR2 U210 (.O(n127),
	.I1(b[3]),
	.I2(FE_OFN10_FE_DBTN8_out_inst_3_3));
   NR2 U211 (.O(n126),
	.I1(FE_OFN3_FE_DBTN15_reg_data_b_4),
	.I2(FE_OFN10_FE_DBTN8_out_inst_3_3));
   NR2 U212 (.O(n125),
	.I1(FE_OFN2_FE_DBTN16_reg_data_b_5),
	.I2(a[4]));
   NR2 U213 (.O(n124),
	.I1(FE_OFN1_FE_DBTN17_reg_data_b_6),
	.I2(a[4]));
   NR2 U214 (.O(n123),
	.I1(FE_OFN0_FE_DBTN18_reg_data_b_7),
	.I2(a[4]));
   NR2 U215 (.O(n122),
	.I1(FE_OFN66_n243),
	.I2(FE_OFN9_FE_DBTN9_out_inst_3_4));
   NR2 U216 (.O(n121),
	.I1(FE_OFN6_FE_DBTN12_reg_data_b_1),
	.I2(FE_OFN9_FE_DBTN9_out_inst_3_4));
   NR2 U217 (.O(n120),
	.I1(FE_OFN5_FE_DBTN13_reg_data_b_2),
	.I2(FE_OFN9_FE_DBTN9_out_inst_3_4));
   NR2 U218 (.O(n119),
	.I1(b[3]),
	.I2(FE_OFN9_FE_DBTN9_out_inst_3_4));
   NR2 U219 (.O(n118),
	.I1(FE_OFN3_FE_DBTN15_reg_data_b_4),
	.I2(a[5]));
   NR2 U220 (.O(n117),
	.I1(FE_OFN2_FE_DBTN16_reg_data_b_5),
	.I2(a[5]));
   NR2 U221 (.O(n116),
	.I1(FE_OFN1_FE_DBTN17_reg_data_b_6),
	.I2(a[5]));
   NR2 U222 (.O(n115),
	.I1(FE_OFN0_FE_DBTN18_reg_data_b_7),
	.I2(a[5]));
   NR2 U223 (.O(n114),
	.I1(FE_OFN66_n243),
	.I2(FE_OFN8_FE_DBTN10_out_inst_3_5));
   NR2 U224 (.O(n113),
	.I1(FE_OFN6_FE_DBTN12_reg_data_b_1),
	.I2(FE_OFN8_FE_DBTN10_out_inst_3_5));
   NR2 U225 (.O(n112),
	.I1(FE_OFN5_FE_DBTN13_reg_data_b_2),
	.I2(FE_OFN8_FE_DBTN10_out_inst_3_5));
   NR2 U226 (.O(n111),
	.I1(b[3]),
	.I2(FE_OFN8_FE_DBTN10_out_inst_3_5));
   NR2 U227 (.O(n110),
	.I1(FE_OFN3_FE_DBTN15_reg_data_b_4),
	.I2(a[6]));
   NR2 U228 (.O(n109),
	.I1(FE_OFN2_FE_DBTN16_reg_data_b_5),
	.I2(a[6]));
   NR2 U229 (.O(n108),
	.I1(b[6]),
	.I2(a[6]));
   NR2 U230 (.O(n107),
	.I1(b[7]),
	.I2(a[6]));
   NR2 U231 (.O(n106),
	.I1(FE_OFN66_n243),
	.I2(FE_OFN7_FE_DBTN11_out_inst_3_6));
   NR2 U232 (.O(n105),
	.I1(FE_OFN7_FE_DBTN11_out_inst_3_6),
	.I2(FE_OFN6_FE_DBTN12_reg_data_b_1));
   NR2 U233 (.O(n104),
	.I1(FE_OFN7_FE_DBTN11_out_inst_3_6),
	.I2(FE_OFN5_FE_DBTN13_reg_data_b_2));
   NR2 U234 (.O(n103),
	.I1(FE_OFN7_FE_DBTN11_out_inst_3_6),
	.I2(b[3]));
   NR2 U235 (.O(n102),
	.I1(FE_OFN7_FE_DBTN11_out_inst_3_6),
	.I2(FE_OFN3_FE_DBTN15_reg_data_b_4));
   NR2 U236 (.O(n101),
	.I1(a[7]),
	.I2(FE_OFN2_FE_DBTN16_reg_data_b_5));
   NR2 U237 (.O(n100),
	.I1(a[7]),
	.I2(b[6]));
endmodule

module alu (
	clk_p_i, 
	reset_n_i, 
	data_a_i, 
	data_b_i, 
	inst_i, 
	data_o);
   input clk_p_i;
   input reset_n_i;
   input [7:0] data_a_i;
   input [7:0] data_b_i;
   input [2:0] inst_i;
   output [15:0] data_o;

   // Internal wires
   wire CTS_2;
   wire CTS_1;
   wire FE_OFN68_n41;
   wire FE_OFN65_n47;
   wire FE_OFN64_n39;
   wire FE_OFN32_i_reset_n_i;
   wire FE_OFN31_i_reset_n_i;
   wire FE_OFN30_i_reset_n_i;
   wire FE_OFN29_i_reset_n_i;
   wire FE_OFN28_i_reset_n_i;
   wire FE_OFN27_i_reset_n_i;
   wire FE_OFN26_i_reset_n_i;
   wire FE_OFN25_i_reset_n_i;
   wire FE_OFN24_i_reset_n_i;
   wire FE_OFN23_FE_DBTN0_n95;
   wire FE_OFN22_FE_DBTN0_n95;
   wire FE_OFN21_FE_DBTN0_n95;
   wire FE_OFN20_FE_DBTN0_n95;
   wire FE_OFN19_FE_DBTN1_n37;
   wire FE_OFN18_FE_DBTN2_n35;
   wire FE_OFN17_FE_DBTN3_n33;
   wire FE_OFN16_FE_DBTN3_n33;
   wire FE_OFN15_FE_DBTN3_n33;
   wire FE_OFN14_FE_DBTN4_n29;
   wire FE_DBTN18_reg_data_b_7;
   wire FE_DBTN17_reg_data_b_6;
   wire FE_DBTN16_reg_data_b_5;
   wire FE_DBTN15_reg_data_b_4;
   wire FE_DBTN14_reg_data_b_3;
   wire FE_DBTN13_reg_data_b_2;
   wire FE_DBTN12_reg_data_b_1;
   wire FE_DBTN11_out_inst_3_6;
   wire FE_DBTN10_out_inst_3_5;
   wire FE_DBTN9_out_inst_3_4;
   wire FE_DBTN8_out_inst_3_3;
   wire FE_DBTN7_out_inst_3_2;
   wire FE_DBTN6_out_inst_3_1;
   wire FE_DBTN5_out_inst_3_0;
   wire FE_DBTN4_n29;
   wire FE_DBTN3_n33;
   wire FE_DBTN2_n35;
   wire FE_DBTN1_n37;
   wire FE_DBTN0_n95;
   wire \reg_data_a[0] ;
   wire out_inst_1_15;
   wire N33;
   wire N34;
   wire N35;
   wire N36;
   wire N37;
   wire N38;
   wire N39;
   wire N40;
   wire N47;
   wire n1;
   wire n24;
   wire n25;
   wire n26;
   wire n27;
   wire n28;
   wire n29;
   wire n30;
   wire n31;
   wire n32;
   wire n33;
   wire n34;
   wire n35;
   wire n36;
   wire n37;
   wire n38;
   wire n39;
   wire n40;
   wire n41;
   wire n43;
   wire n44;
   wire n45;
   wire n46;
   wire n47;
   wire n48;
   wire n49;
   wire n50;
   wire n51;
   wire n52;
   wire n53;
   wire n54;
   wire n55;
   wire n56;
   wire n57;
   wire n58;
   wire n59;
   wire n60;
   wire n61;
   wire n62;
   wire n63;
   wire n64;
   wire n65;
   wire n66;
   wire n67;
   wire n68;
   wire n69;
   wire n70;
   wire n71;
   wire n72;
   wire n73;
   wire n74;
   wire n75;
   wire n76;
   wire n77;
   wire n78;
   wire n79;
   wire n80;
   wire n81;
   wire n82;
   wire n83;
   wire \add_51/carry[2] ;
   wire \add_51/carry[3] ;
   wire \add_51/carry[4] ;
   wire \add_51/carry[5] ;
   wire \add_51/carry[6] ;
   wire \add_51/carry[7] ;
   wire \add_51/carry[8] ;
   wire \add_51/A[0] ;
   wire \add_51/A[1] ;
   wire \add_51/A[2] ;
   wire \add_51/A[3] ;
   wire \add_51/A[4] ;
   wire \add_51/A[5] ;
   wire \add_51/A[6] ;
   wire \add_51/A[7] ;
   wire n89;
   wire n95;
   wire n102;
   wire n103;
   wire n106;
   wire n108;
   wire n110;
   wire n111;
   wire [15:0] ALU_d2_w;
   wire [7:0] reg_data_b;
   wire [8:0] out_inst_0;
   wire [7:0] out_inst_1;
   wire [15:0] out_inst_2;
   wire [6:0] out_inst_3;
   wire [2:0] reg_inst;
   wire [2:0] inst_i_v;

   INV12CK CTS_ccl_a_inv_00003 (.O(CTS_1),
	.I(CTS_2));
   INV12CK CTS_ccl_a_inv_00006 (.O(CTS_2),
	.I(clk_p_i));
   BUF1S FE_OFC68_n41 (.O(FE_OFN68_n41),
	.I(n41));
   BUF1S FE_OFC65_n47 (.O(FE_OFN65_n47),
	.I(n47));
   BUF1S FE_OFC64_n39 (.O(FE_OFN64_n39),
	.I(n39));
   BUF1S FE_OFC32_i_reset_n_i (.O(FE_OFN32_i_reset_n_i),
	.I(FE_OFN31_i_reset_n_i));
   BUF1S FE_OFC31_i_reset_n_i (.O(FE_OFN31_i_reset_n_i),
	.I(FE_OFN28_i_reset_n_i));
   INV1S FE_OFC30_i_reset_n_i (.O(FE_OFN30_i_reset_n_i),
	.I(FE_OFN27_i_reset_n_i));
   INV1S FE_OFC29_i_reset_n_i (.O(FE_OFN29_i_reset_n_i),
	.I(FE_OFN27_i_reset_n_i));
   BUF1S FE_OFC28_i_reset_n_i (.O(FE_OFN28_i_reset_n_i),
	.I(FE_OFN26_i_reset_n_i));
   INV1S FE_OFC27_i_reset_n_i (.O(FE_OFN27_i_reset_n_i),
	.I(FE_OFN25_i_reset_n_i));
   INV1S FE_OFC26_i_reset_n_i (.O(FE_OFN26_i_reset_n_i),
	.I(FE_OFN24_i_reset_n_i));
   INV1S FE_OFC25_i_reset_n_i (.O(FE_OFN25_i_reset_n_i),
	.I(FE_OFN24_i_reset_n_i));
   INV1S FE_OFC24_i_reset_n_i (.O(FE_OFN24_i_reset_n_i),
	.I(reset_n_i));
   INV1S FE_OFC23_FE_DBTN0_n95 (.O(FE_OFN23_FE_DBTN0_n95),
	.I(FE_OFN20_FE_DBTN0_n95));
   INV1S FE_OFC22_FE_DBTN0_n95 (.O(FE_OFN22_FE_DBTN0_n95),
	.I(FE_OFN20_FE_DBTN0_n95));
   BUF1S FE_OFC21_FE_DBTN0_n95 (.O(FE_OFN21_FE_DBTN0_n95),
	.I(FE_DBTN0_n95));
   INV1S FE_OFC20_FE_DBTN0_n95 (.O(FE_OFN20_FE_DBTN0_n95),
	.I(FE_DBTN0_n95));
   BUF1S FE_OFC19_FE_DBTN1_n37 (.O(FE_OFN19_FE_DBTN1_n37),
	.I(FE_DBTN1_n37));
   BUF1S FE_OFC18_FE_DBTN2_n35 (.O(FE_OFN18_FE_DBTN2_n35),
	.I(FE_DBTN2_n35));
   BUF1S FE_OFC17_FE_DBTN3_n33 (.O(FE_OFN17_FE_DBTN3_n33),
	.I(FE_OFN15_FE_DBTN3_n33));
   BUF1S FE_OFC16_FE_DBTN3_n33 (.O(FE_OFN16_FE_DBTN3_n33),
	.I(FE_DBTN3_n33));
   BUF1S FE_OFC15_FE_DBTN3_n33 (.O(FE_OFN15_FE_DBTN3_n33),
	.I(FE_DBTN3_n33));
   BUF1S FE_OFC14_FE_DBTN4_n29 (.O(FE_OFN14_FE_DBTN4_n29),
	.I(FE_DBTN4_n29));
   INV1S FE_DBTC18_reg_data_b_7 (.O(FE_DBTN18_reg_data_b_7),
	.I(reg_data_b[7]));
   INV1S FE_DBTC17_reg_data_b_6 (.O(FE_DBTN17_reg_data_b_6),
	.I(reg_data_b[6]));
   INV1S FE_DBTC16_reg_data_b_5 (.O(FE_DBTN16_reg_data_b_5),
	.I(reg_data_b[5]));
   INV1S FE_DBTC15_reg_data_b_4 (.O(FE_DBTN15_reg_data_b_4),
	.I(reg_data_b[4]));
   INV1S FE_DBTC14_reg_data_b_3 (.O(FE_DBTN14_reg_data_b_3),
	.I(reg_data_b[3]));
   INV1S FE_DBTC13_reg_data_b_2 (.O(FE_DBTN13_reg_data_b_2),
	.I(reg_data_b[2]));
   INV1S FE_DBTC12_reg_data_b_1 (.O(FE_DBTN12_reg_data_b_1),
	.I(reg_data_b[1]));
   INV1S FE_DBTC11_out_inst_3_6 (.O(FE_DBTN11_out_inst_3_6),
	.I(out_inst_3[6]));
   INV1S FE_DBTC10_out_inst_3_5 (.O(FE_DBTN10_out_inst_3_5),
	.I(out_inst_3[5]));
   INV1S FE_DBTC9_out_inst_3_4 (.O(FE_DBTN9_out_inst_3_4),
	.I(out_inst_3[4]));
   INV1S FE_DBTC8_out_inst_3_3 (.O(FE_DBTN8_out_inst_3_3),
	.I(out_inst_3[3]));
   INV1S FE_DBTC7_out_inst_3_2 (.O(FE_DBTN7_out_inst_3_2),
	.I(out_inst_3[2]));
   INV1S FE_DBTC6_out_inst_3_1 (.O(FE_DBTN6_out_inst_3_1),
	.I(out_inst_3[1]));
   INV1S FE_DBTC5_out_inst_3_0 (.O(FE_DBTN5_out_inst_3_0),
	.I(out_inst_3[0]));
   INV1S FE_DBTC4_n29 (.O(FE_DBTN4_n29),
	.I(n29));
   INV1S FE_DBTC3_n33 (.O(FE_DBTN3_n33),
	.I(n33));
   INV1S FE_DBTC2_n35 (.O(FE_DBTN2_n35),
	.I(n35));
   INV1S FE_DBTC1_n37 (.O(FE_DBTN1_n37),
	.I(n37));
   INV1S FE_DBTC0_n95 (.O(FE_DBTN0_n95),
	.I(n95));
   OA222 U76 (.O(n31),
	.A1(n32),
	.A2(n33),
	.B1(n34),
	.B2(n35),
	.C1(n36),
	.C2(n37));
   ND2 U77 (.O(n25),
	.I1(inst_i[0]),
	.I2(n103));
   ND2 U78 (.O(ALU_d2_w[9]),
	.I1(n40),
	.I2(FE_OFN68_n41));
   ND2 U79 (.O(n43),
	.I1(out_inst_0[8]),
	.I2(n39));
   AO112 U80 (.O(ALU_d2_w[7]),
	.A1(n45),
	.B1(n46),
	.C1(out_inst_0[7]),
	.C2(n39));
   AO222 U81 (.O(n46),
	.A1(n47),
	.A2(out_inst_1[7]),
	.B1(N39),
	.B2(FE_DBTN0_n95),
	.C1(FE_DBTN2_n35),
	.C2(n48));
   OR3B2 U82 (.O(ALU_d2_w[6]),
	.I1(n49),
	.B1(n50),
	.B2(n51));
   AO222 U83 (.O(n49),
	.A1(out_inst_2[6]),
	.A2(FE_DBTN3_n33),
	.B1(out_inst_3[6]),
	.B2(FE_DBTN1_n37),
	.C1(out_inst_0[6]),
	.C2(n39));
   OR3B2 U84 (.O(ALU_d2_w[5]),
	.I1(n53),
	.B1(n54),
	.B2(n55));
   AO222 U85 (.O(n53),
	.A1(out_inst_2[5]),
	.A2(FE_OFN16_FE_DBTN3_n33),
	.B1(out_inst_3[5]),
	.B2(FE_OFN19_FE_DBTN1_n37),
	.C1(out_inst_0[5]),
	.C2(FE_OFN64_n39));
   OR3B2 U86 (.O(ALU_d2_w[4]),
	.I1(n57),
	.B1(n58),
	.B2(n59));
   AO222 U87 (.O(n57),
	.A1(out_inst_2[4]),
	.A2(FE_OFN16_FE_DBTN3_n33),
	.B1(out_inst_3[4]),
	.B2(FE_OFN19_FE_DBTN1_n37),
	.C1(out_inst_0[4]),
	.C2(FE_OFN64_n39));
   OR3B2 U88 (.O(ALU_d2_w[3]),
	.I1(n61),
	.B1(n62),
	.B2(n63));
   AO222 U89 (.O(n61),
	.A1(out_inst_2[3]),
	.A2(FE_OFN16_FE_DBTN3_n33),
	.B1(out_inst_3[3]),
	.B2(FE_OFN19_FE_DBTN1_n37),
	.C1(out_inst_0[3]),
	.C2(FE_OFN64_n39));
   OR3B2 U90 (.O(ALU_d2_w[2]),
	.I1(n65),
	.B1(n66),
	.B2(n67));
   AO222 U91 (.O(n65),
	.A1(out_inst_2[2]),
	.A2(FE_OFN16_FE_DBTN3_n33),
	.B1(out_inst_3[2]),
	.B2(FE_OFN19_FE_DBTN1_n37),
	.C1(out_inst_0[2]),
	.C2(FE_OFN64_n39));
   OR3B2 U92 (.O(ALU_d2_w[1]),
	.I1(n69),
	.B1(n70),
	.B2(n71));
   AO222 U93 (.O(n69),
	.A1(out_inst_2[1]),
	.A2(FE_OFN16_FE_DBTN3_n33),
	.B1(out_inst_3[1]),
	.B2(FE_OFN19_FE_DBTN1_n37),
	.C1(out_inst_0[1]),
	.C2(FE_OFN64_n39));
   ND2 U94 (.O(ALU_d2_w[15]),
	.I1(n73),
	.I2(n41));
   ND2 U95 (.O(ALU_d2_w[14]),
	.I1(n74),
	.I2(n41));
   ND2 U96 (.O(ALU_d2_w[13]),
	.I1(n75),
	.I2(n41));
   ND2 U97 (.O(ALU_d2_w[12]),
	.I1(n76),
	.I2(FE_OFN68_n41));
   ND2 U98 (.O(ALU_d2_w[11]),
	.I1(n77),
	.I2(FE_OFN68_n41));
   ND2 U99 (.O(ALU_d2_w[10]),
	.I1(n78),
	.I2(FE_OFN68_n41));
   OR3B2 U100 (.O(ALU_d2_w[0]),
	.I1(n80),
	.B1(n81),
	.B2(n82));
   AO222 U101 (.O(n80),
	.A1(out_inst_2[0]),
	.A2(FE_OFN16_FE_DBTN3_n33),
	.B1(out_inst_3[0]),
	.B2(FE_OFN19_FE_DBTN1_n37),
	.C1(n83),
	.C2(FE_OFN64_n39));
   alu_DW01_add_0 add_43 (.A({ n1,
		out_inst_3,
		\reg_data_a[0]  }),
	.B({ n1,
		reg_data_b }),
	.CI(n1),
	.SUM(out_inst_0));
   alu_DW01_sub_0 r306 (.A({ n1,
		reg_data_b }),
	.B({ n1,
		out_inst_3,
		\reg_data_a[0]  }),
	.CI(n1),
	.DIFF({ out_inst_1_15,
		out_inst_1 }),
	.FE_DBTN5_out_inst_3_0(FE_DBTN5_out_inst_3_0),
	.FE_DBTN10_out_inst_3_5(FE_DBTN10_out_inst_3_5),
	.FE_DBTN11_out_inst_3_6(FE_DBTN11_out_inst_3_6),
	.FE_DBTN9_out_inst_3_4(FE_DBTN9_out_inst_3_4),
	.FE_DBTN6_out_inst_3_1(FE_DBTN6_out_inst_3_1),
	.FE_DBTN8_out_inst_3_3(FE_DBTN8_out_inst_3_3),
	.FE_DBTN7_out_inst_3_2(FE_DBTN7_out_inst_3_2));
   alu_DW_mult_uns_0 mult_45 (.a({ FE_DBTN11_out_inst_3_6,
		FE_DBTN10_out_inst_3_5,
		FE_DBTN9_out_inst_3_4,
		FE_DBTN8_out_inst_3_3,
		FE_DBTN7_out_inst_3_2,
		FE_DBTN6_out_inst_3_1,
		FE_DBTN5_out_inst_3_0,
		\reg_data_a[0]  }),
	.b({ FE_DBTN18_reg_data_b_7,
		FE_DBTN17_reg_data_b_6,
		FE_DBTN16_reg_data_b_5,
		FE_DBTN15_reg_data_b_4,
		FE_DBTN14_reg_data_b_3,
		FE_DBTN13_reg_data_b_2,
		FE_DBTN12_reg_data_b_1,
		reg_data_b[0] }),
	.product(out_inst_2));
   HA1 \add_51/U1_1_1  (.S(N33),
	.C(\add_51/carry[2] ),
	.A(\add_51/A[1] ),
	.B(\add_51/A[0] ));
   HA1 \add_51/U1_1_2  (.S(N34),
	.C(\add_51/carry[3] ),
	.A(\add_51/A[2] ),
	.B(\add_51/carry[2] ));
   HA1 \add_51/U1_1_3  (.S(N35),
	.C(\add_51/carry[4] ),
	.A(\add_51/A[3] ),
	.B(\add_51/carry[3] ));
   HA1 \add_51/U1_1_4  (.S(N36),
	.C(\add_51/carry[5] ),
	.A(\add_51/A[4] ),
	.B(\add_51/carry[4] ));
   HA1 \add_51/U1_1_5  (.S(N37),
	.C(\add_51/carry[6] ),
	.A(\add_51/A[5] ),
	.B(\add_51/carry[5] ));
   HA1 \add_51/U1_1_6  (.S(N38),
	.C(\add_51/carry[7] ),
	.A(\add_51/A[6] ),
	.B(\add_51/carry[6] ));
   HA1 \add_51/U1_1_7  (.S(N39),
	.C(\add_51/carry[8] ),
	.A(\add_51/A[7] ),
	.B(\add_51/carry[7] ));
   QDFFRBN \reg_inst_reg[0]  (.Q(reg_inst[0]),
	.D(inst_i_v[0]),
	.CK(CTS_1),
	.RB(FE_OFN26_i_reset_n_i));
   QDFFRBN \reg_inst_reg[2]  (.Q(reg_inst[2]),
	.D(inst_i_v[2]),
	.CK(CTS_1),
	.RB(FE_OFN26_i_reset_n_i));
   QDFFRBN \reg_inst_reg[1]  (.Q(reg_inst[1]),
	.D(inst_i_v[1]),
	.CK(CTS_1),
	.RB(FE_OFN26_i_reset_n_i));
   QDFFRBN \reg_data_b_reg[7]  (.Q(reg_data_b[7]),
	.D(data_b_i[7]),
	.CK(CTS_1),
	.RB(reset_n_i));
   QDFFRBN \reg_data_b_reg[6]  (.Q(reg_data_b[6]),
	.D(data_b_i[6]),
	.CK(CTS_1),
	.RB(reset_n_i));
   QDFFRBN \reg_data_b_reg[5]  (.Q(reg_data_b[5]),
	.D(data_b_i[5]),
	.CK(CTS_1),
	.RB(reset_n_i));
   QDFFRBN \reg_data_b_reg[4]  (.Q(reg_data_b[4]),
	.D(data_b_i[4]),
	.CK(CTS_1),
	.RB(FE_OFN25_i_reset_n_i));
   QDFFRBN \reg_data_b_reg[3]  (.Q(reg_data_b[3]),
	.D(data_b_i[3]),
	.CK(CTS_1),
	.RB(FE_OFN25_i_reset_n_i));
   QDFFRBN \reg_data_b_reg[1]  (.Q(reg_data_b[1]),
	.D(data_b_i[1]),
	.CK(CTS_1),
	.RB(FE_OFN29_i_reset_n_i));
   QDFFRBN \reg_data_a_reg[7]  (.Q(out_inst_3[6]),
	.D(data_a_i[7]),
	.CK(CTS_1),
	.RB(FE_OFN25_i_reset_n_i));
   QDFFRBN \reg_data_a_reg[6]  (.Q(out_inst_3[5]),
	.D(data_a_i[6]),
	.CK(CTS_1),
	.RB(FE_OFN29_i_reset_n_i));
   QDFFRBN \reg_data_a_reg[5]  (.Q(out_inst_3[4]),
	.D(data_a_i[5]),
	.CK(CTS_1),
	.RB(FE_OFN30_i_reset_n_i));
   QDFFRBN \reg_data_a_reg[4]  (.Q(out_inst_3[3]),
	.D(data_a_i[4]),
	.CK(CTS_1),
	.RB(FE_OFN26_i_reset_n_i));
   QDFFRBN \reg_data_a_reg[3]  (.Q(out_inst_3[2]),
	.D(data_a_i[3]),
	.CK(CTS_1),
	.RB(FE_OFN28_i_reset_n_i));
   QDFFRBN \reg_data_a_reg[2]  (.Q(out_inst_3[1]),
	.D(data_a_i[2]),
	.CK(CTS_1),
	.RB(FE_OFN28_i_reset_n_i));
   QDFFRBN \reg_data_b_reg[0]  (.Q(reg_data_b[0]),
	.D(data_b_i[0]),
	.CK(CTS_1),
	.RB(FE_OFN29_i_reset_n_i));
   QDFFRBN \reg_data_b_reg[2]  (.Q(reg_data_b[2]),
	.D(data_b_i[2]),
	.CK(CTS_1),
	.RB(FE_OFN30_i_reset_n_i));
   QDFFRBN \reg_data_a_reg[1]  (.Q(out_inst_3[0]),
	.D(data_a_i[1]),
	.CK(CTS_1),
	.RB(FE_OFN28_i_reset_n_i));
   QDFFRBN \reg_data_a_reg[0]  (.Q(\reg_data_a[0] ),
	.D(data_a_i[0]),
	.CK(CTS_1),
	.RB(FE_OFN28_i_reset_n_i));
   QDFFRBN \ALU_d2_r_reg[1]  (.Q(data_o[1]),
	.D(ALU_d2_w[1]),
	.CK(CTS_1),
	.RB(FE_OFN30_i_reset_n_i));
   QDFFRBN \ALU_d2_r_reg[4]  (.Q(data_o[4]),
	.D(ALU_d2_w[4]),
	.CK(CTS_1),
	.RB(FE_OFN31_i_reset_n_i));
   QDFFRBN \ALU_d2_r_reg[2]  (.Q(data_o[2]),
	.D(ALU_d2_w[2]),
	.CK(CTS_1),
	.RB(FE_OFN30_i_reset_n_i));
   QDFFRBN \ALU_d2_r_reg[5]  (.Q(data_o[5]),
	.D(ALU_d2_w[5]),
	.CK(CTS_1),
	.RB(FE_OFN32_i_reset_n_i));
   QDFFRBN \ALU_d2_r_reg[8]  (.Q(data_o[8]),
	.D(ALU_d2_w[8]),
	.CK(CTS_1),
	.RB(FE_OFN32_i_reset_n_i));
   QDFFRBN \ALU_d2_r_reg[0]  (.Q(data_o[0]),
	.D(ALU_d2_w[0]),
	.CK(CTS_1),
	.RB(FE_OFN30_i_reset_n_i));
   QDFFRBN \ALU_d2_r_reg[6]  (.Q(data_o[6]),
	.D(ALU_d2_w[6]),
	.CK(CTS_1),
	.RB(FE_OFN32_i_reset_n_i));
   QDFFRBN \ALU_d2_r_reg[3]  (.Q(data_o[3]),
	.D(ALU_d2_w[3]),
	.CK(CTS_1),
	.RB(FE_OFN30_i_reset_n_i));
   QDFFRBN \ALU_d2_r_reg[9]  (.Q(data_o[9]),
	.D(ALU_d2_w[9]),
	.CK(CTS_1),
	.RB(FE_OFN32_i_reset_n_i));
   QDFFRBN \ALU_d2_r_reg[7]  (.Q(data_o[7]),
	.D(ALU_d2_w[7]),
	.CK(CTS_1),
	.RB(FE_OFN31_i_reset_n_i));
   QDFFRBN \ALU_d2_r_reg[10]  (.Q(data_o[10]),
	.D(ALU_d2_w[10]),
	.CK(CTS_1),
	.RB(FE_OFN32_i_reset_n_i));
   QDFFRBN \ALU_d2_r_reg[11]  (.Q(data_o[11]),
	.D(ALU_d2_w[11]),
	.CK(CTS_1),
	.RB(FE_OFN32_i_reset_n_i));
   QDFFRBN \ALU_d2_r_reg[12]  (.Q(data_o[12]),
	.D(ALU_d2_w[12]),
	.CK(CTS_1),
	.RB(FE_OFN31_i_reset_n_i));
   QDFFRBN \ALU_d2_r_reg[13]  (.Q(data_o[13]),
	.D(ALU_d2_w[13]),
	.CK(CTS_1),
	.RB(FE_OFN31_i_reset_n_i));
   QDFFRBN \ALU_d2_r_reg[15]  (.Q(data_o[15]),
	.D(ALU_d2_w[15]),
	.CK(CTS_1),
	.RB(FE_OFN31_i_reset_n_i));
   QDFFRBN \ALU_d2_r_reg[14]  (.Q(data_o[14]),
	.D(ALU_d2_w[14]),
	.CK(CTS_1),
	.RB(FE_OFN28_i_reset_n_i));
   NR2 U107 (.O(n89),
	.I1(\add_51/carry[8] ),
	.I2(out_inst_1_15));
   AOI22S U113 (.O(n74),
	.A1(N47),
	.A2(FE_OFN22_FE_DBTN0_n95),
	.B1(out_inst_2[14]),
	.B2(FE_OFN15_FE_DBTN3_n33));
   AOI22S U114 (.O(n77),
	.A1(n89),
	.A2(FE_OFN23_FE_DBTN0_n95),
	.B1(out_inst_2[11]),
	.B2(FE_OFN17_FE_DBTN3_n33));
   AOI22S U115 (.O(n76),
	.A1(N47),
	.A2(FE_OFN23_FE_DBTN0_n95),
	.B1(out_inst_2[12]),
	.B2(FE_OFN17_FE_DBTN3_n33));
   AOI22S U116 (.O(n75),
	.A1(n89),
	.A2(FE_OFN23_FE_DBTN0_n95),
	.B1(out_inst_2[13]),
	.B2(FE_OFN17_FE_DBTN3_n33));
   AOI22S U117 (.O(n73),
	.A1(N47),
	.A2(FE_OFN22_FE_DBTN0_n95),
	.B1(out_inst_2[15]),
	.B2(FE_OFN15_FE_DBTN3_n33));
   INV1S U118 (.O(n102),
	.I(out_inst_1_15));
   AOI22S U119 (.O(n78),
	.A1(n89),
	.A2(FE_OFN23_FE_DBTN0_n95),
	.B1(out_inst_2[10]),
	.B2(FE_OFN17_FE_DBTN3_n33));
   AOI22S U120 (.O(n40),
	.A1(N47),
	.A2(FE_OFN23_FE_DBTN0_n95),
	.B1(out_inst_2[9]),
	.B2(FE_OFN17_FE_DBTN3_n33));
   AOI22S U121 (.O(n41),
	.A1(out_inst_1_15),
	.A2(n108),
	.B1(n102),
	.B2(FE_DBTN4_n29));
   OAI12HS U122 (.O(n47),
	.A1(n79),
	.B1(out_inst_1_15),
	.B2(n26));
   OR2 U123 (.O(n95),
	.I1(n26),
	.I2(n102));
   ND3 U125 (.O(ALU_d2_w[8]),
	.I1(n41),
	.I2(n43),
	.I3(n44));
   AOI22S U126 (.O(n44),
	.A1(N40),
	.A2(FE_DBTN0_n95),
	.B1(out_inst_2[8]),
	.B2(FE_OFN15_FE_DBTN3_n33));
   INV1S U127 (.O(\add_51/A[7] ),
	.I(out_inst_1[7]));
   INV1S U128 (.O(\add_51/A[6] ),
	.I(out_inst_1[6]));
   INV1S U129 (.O(\add_51/A[5] ),
	.I(out_inst_1[5]));
   INV1S U130 (.O(\add_51/A[4] ),
	.I(out_inst_1[4]));
   INV1S U131 (.O(\add_51/A[0] ),
	.I(out_inst_1[0]));
   INV1S U132 (.O(\add_51/A[3] ),
	.I(out_inst_1[3]));
   INV1S U133 (.O(\add_51/A[2] ),
	.I(out_inst_1[2]));
   INV1S U134 (.O(\add_51/A[1] ),
	.I(out_inst_1[1]));
   INV1S U139 (.O(n108),
	.I(n79));
   MOAI1S U144 (.O(n45),
	.A1(out_inst_1[7]),
	.A2(n29),
	.B1(out_inst_2[7]),
	.B2(FE_OFN15_FE_DBTN3_n33));
   XOR2HS U145 (.O(n48),
	.I1(reg_data_b[7]),
	.I2(out_inst_3[6]));
   MOAI1S U146 (.O(n24),
	.A1(n25),
	.A2(n26),
	.B1(n27),
	.B2(n28));
   ND3 U147 (.O(n28),
	.I1(inst_i[1]),
	.I2(inst_i[0]),
	.I3(inst_i[2]));
   OAI112HS U148 (.O(n27),
	.A1(n30),
	.B1(n31),
	.C1(n25),
	.C2(n29));
   NR2 U149 (.O(n30),
	.I1(n39),
	.I2(n108));
   AOI22S U150 (.O(n51),
	.A1(FE_DBTN2_n35),
	.A2(n52),
	.B1(FE_DBTN4_n29),
	.B2(\add_51/A[6] ));
   AOI22S U151 (.O(n50),
	.A1(N38),
	.A2(FE_DBTN0_n95),
	.B1(n47),
	.B2(out_inst_1[6]));
   AOI22S U152 (.O(n55),
	.A1(FE_DBTN2_n35),
	.A2(n56),
	.B1(FE_OFN14_FE_DBTN4_n29),
	.B2(\add_51/A[5] ));
   AOI22S U153 (.O(n54),
	.A1(N37),
	.A2(FE_OFN21_FE_DBTN0_n95),
	.B1(FE_OFN65_n47),
	.B2(out_inst_1[5]));
   AOI22S U154 (.O(n59),
	.A1(FE_OFN18_FE_DBTN2_n35),
	.A2(n60),
	.B1(FE_OFN14_FE_DBTN4_n29),
	.B2(\add_51/A[4] ));
   AOI22S U155 (.O(n58),
	.A1(N36),
	.A2(FE_OFN21_FE_DBTN0_n95),
	.B1(FE_OFN65_n47),
	.B2(out_inst_1[4]));
   AOI22S U156 (.O(n63),
	.A1(FE_OFN18_FE_DBTN2_n35),
	.A2(n64),
	.B1(FE_OFN14_FE_DBTN4_n29),
	.B2(\add_51/A[3] ));
   AOI22S U157 (.O(n62),
	.A1(N35),
	.A2(FE_OFN21_FE_DBTN0_n95),
	.B1(FE_OFN65_n47),
	.B2(out_inst_1[3]));
   AOI22S U158 (.O(n67),
	.A1(FE_OFN18_FE_DBTN2_n35),
	.A2(n68),
	.B1(FE_OFN14_FE_DBTN4_n29),
	.B2(\add_51/A[2] ));
   AOI22S U159 (.O(n66),
	.A1(N34),
	.A2(FE_OFN21_FE_DBTN0_n95),
	.B1(FE_OFN65_n47),
	.B2(out_inst_1[2]));
   AOI22S U160 (.O(n71),
	.A1(FE_OFN18_FE_DBTN2_n35),
	.A2(n72),
	.B1(FE_OFN14_FE_DBTN4_n29),
	.B2(\add_51/A[1] ));
   AOI22S U161 (.O(n70),
	.A1(N33),
	.A2(FE_OFN21_FE_DBTN0_n95),
	.B1(FE_OFN65_n47),
	.B2(out_inst_1[1]));
   AOI22S U162 (.O(n82),
	.A1(FE_OFN18_FE_DBTN2_n35),
	.A2(n83),
	.B1(FE_OFN14_FE_DBTN4_n29),
	.B2(\add_51/A[0] ));
   AOI22S U163 (.O(n81),
	.A1(out_inst_1[0]),
	.A2(FE_OFN21_FE_DBTN0_n95),
	.B1(FE_OFN65_n47),
	.B2(out_inst_1[0]));
   NR2 U164 (.O(n38),
	.I1(inst_i[1]),
	.I2(inst_i[2]));
   MOAI1S U165 (.O(inst_i_v[1]),
	.A1(n24),
	.A2(n111),
	.B1(n24),
	.B2(inst_i[1]));
   MOAI1S U166 (.O(inst_i_v[2]),
	.A1(n24),
	.A2(n110),
	.B1(n24),
	.B2(inst_i[2]));
   MOAI1S U167 (.O(inst_i_v[0]),
	.A1(n24),
	.A2(n106),
	.B1(n24),
	.B2(inst_i[0]));
   NR2 U168 (.O(n32),
	.I1(n38),
	.I2(inst_i[0]));
   MAOI1 U169 (.O(n34),
	.A1(inst_i[0]),
	.A2(n103),
	.B1(inst_i[0]),
	.B2(inst_i[2]));
   AOI12HS U170 (.O(n36),
	.A1(n38),
	.B1(inst_i[1]),
	.B2(inst_i[2]));
   INV1S U171 (.O(n103),
	.I(inst_i[1]));
   NR3 U172 (.O(n39),
	.I1(reg_inst[1]),
	.I2(reg_inst[2]),
	.I3(reg_inst[0]));
   INV1S U173 (.O(n110),
	.I(reg_inst[2]));
   INV1S U174 (.O(n111),
	.I(reg_inst[1]));
   INV1S U175 (.O(n106),
	.I(reg_inst[0]));
   ND3 U176 (.O(n26),
	.I1(reg_inst[2]),
	.I2(n106),
	.I3(reg_inst[1]));
   ND3 U177 (.O(n33),
	.I1(n106),
	.I2(n110),
	.I3(reg_inst[1]));
   ND3 U178 (.O(n29),
	.I1(n106),
	.I2(n111),
	.I3(reg_inst[2]));
   ND3 U179 (.O(n79),
	.I1(n111),
	.I2(n110),
	.I3(reg_inst[0]));
   ND3 U180 (.O(n35),
	.I1(reg_inst[0]),
	.I2(n111),
	.I3(reg_inst[2]));
   ND3 U181 (.O(n37),
	.I1(reg_inst[0]),
	.I2(n110),
	.I3(reg_inst[1]));
   XOR2HS U182 (.O(n83),
	.I1(reg_data_b[0]),
	.I2(\reg_data_a[0] ));
   XOR2HS U183 (.O(n52),
	.I1(reg_data_b[6]),
	.I2(out_inst_3[5]));
   XOR2HS U184 (.O(n56),
	.I1(reg_data_b[5]),
	.I2(out_inst_3[4]));
   XOR2HS U185 (.O(n60),
	.I1(reg_data_b[4]),
	.I2(out_inst_3[3]));
   XOR2HS U186 (.O(n64),
	.I1(reg_data_b[3]),
	.I2(out_inst_3[2]));
   XOR2HS U187 (.O(n68),
	.I1(reg_data_b[2]),
	.I2(out_inst_3[1]));
   XOR2HS U188 (.O(n72),
	.I1(reg_data_b[1]),
	.I2(out_inst_3[0]));
   XOR2HS U192 (.O(N40),
	.I1(\add_51/carry[8] ),
	.I2(n102));
   NR2 U193 (.O(N47),
	.I1(\add_51/carry[8] ),
	.I2(out_inst_1_15));
endmodule

module CHIP (
	clk_p_i, 
	reset_n_i, 
	data_a_i, 
	data_b_i, 
	inst_i, 
	data_o);
   input clk_p_i;
   input reset_n_i;
   input [7:0] data_a_i;
   input [7:0] data_b_i;
   input [2:0] inst_i;
   output [15:0] data_o;

   // Internal wires
   wire FE_OFN63_n_logic1;
   wire FE_OFN62_n_logic1;
   wire FE_OFN61_n_logic1;
   wire FE_OFN60_n_logic1;
   wire FE_OFN59_n_logic0;
   wire FE_OFN58_n_logic0;
   wire FE_OFN57_n_logic0;
   wire FE_OFN56_n_logic0;
   wire FE_OFN55_n_logic0;
   wire FE_OFN54_n_logic0;
   wire FE_OFN53_n_logic0;
   wire FE_OFN52_n_logic0;
   wire FE_OFN51_n_logic0;
   wire FE_OFN50_n_logic0;
   wire FE_OFN49_n_logic0;
   wire FE_OFN48_n_logic0;
   wire FE_OFN47_n_logic0;
   wire FE_OFN46_n_logic0;
   wire FE_OFN45_n_logic0;
   wire FE_OFN44_n_logic0;
   wire FE_OFN43_n_logic0;
   wire FE_OFN42_n_logic0;
   wire FE_OFN41_n_logic0;
   wire FE_OFN40_n_logic0;
   wire FE_OFN39_n_logic0;
   wire FE_OFN38_n_logic0;
   wire FE_OFN37_n_logic0;
   wire FE_OFN36_n_logic0;
   wire FE_OFN35_n_logic0;
   wire FE_OFN34_n_logic0;
   wire FE_OFN33_n_logic0;
   wire [7:0] i_data_a_i;
   wire [7:0] i_data_b_i;
   wire [2:0] i_inst_i;
   wire [15:0] i_data_o;
   wire i_clk_p_i;
   wire i_reset_n_i;
   wire n_logic0;
   wire n_logic1;

   BUF1 FE_OFC63_n_logic1 (.O(FE_OFN63_n_logic1),
	.I(FE_OFN61_n_logic1));
   INV2 FE_OFC62_n_logic1 (.O(FE_OFN62_n_logic1),
	.I(FE_OFN60_n_logic1));
   INV2 FE_OFC61_n_logic1 (.O(FE_OFN61_n_logic1),
	.I(FE_OFN60_n_logic1));
   INV1S FE_OFC60_n_logic1 (.O(FE_OFN60_n_logic1),
	.I(n_logic1));
   BUF1S FE_OFC59_n_logic0 (.O(FE_OFN59_n_logic0),
	.I(FE_OFN56_n_logic0));
   BUF1S FE_OFC58_n_logic0 (.O(FE_OFN58_n_logic0),
	.I(FE_OFN54_n_logic0));
   BUF1S FE_OFC57_n_logic0 (.O(FE_OFN57_n_logic0),
	.I(FE_OFN53_n_logic0));
   BUF1S FE_OFC56_n_logic0 (.O(FE_OFN56_n_logic0),
	.I(FE_OFN52_n_logic0));
   BUF1S FE_OFC55_n_logic0 (.O(FE_OFN55_n_logic0),
	.I(FE_OFN51_n_logic0));
   BUF1S FE_OFC54_n_logic0 (.O(FE_OFN54_n_logic0),
	.I(FE_OFN50_n_logic0));
   BUF1S FE_OFC53_n_logic0 (.O(FE_OFN53_n_logic0),
	.I(FE_OFN49_n_logic0));
   BUF1S FE_OFC52_n_logic0 (.O(FE_OFN52_n_logic0),
	.I(FE_OFN48_n_logic0));
   BUF1S FE_OFC51_n_logic0 (.O(FE_OFN51_n_logic0),
	.I(FE_OFN47_n_logic0));
   BUF1S FE_OFC50_n_logic0 (.O(FE_OFN50_n_logic0),
	.I(FE_OFN46_n_logic0));
   BUF1S FE_OFC49_n_logic0 (.O(FE_OFN49_n_logic0),
	.I(FE_OFN45_n_logic0));
   BUF1S FE_OFC48_n_logic0 (.O(FE_OFN48_n_logic0),
	.I(FE_OFN44_n_logic0));
   BUF1S FE_OFC47_n_logic0 (.O(FE_OFN47_n_logic0),
	.I(FE_OFN43_n_logic0));
   BUF1S FE_OFC46_n_logic0 (.O(FE_OFN46_n_logic0),
	.I(FE_OFN42_n_logic0));
   BUF1S FE_OFC45_n_logic0 (.O(FE_OFN45_n_logic0),
	.I(FE_OFN41_n_logic0));
   BUF1S FE_OFC44_n_logic0 (.O(FE_OFN44_n_logic0),
	.I(FE_OFN40_n_logic0));
   BUF1 FE_OFC43_n_logic0 (.O(FE_OFN43_n_logic0),
	.I(FE_OFN39_n_logic0));
   BUF1S FE_OFC42_n_logic0 (.O(FE_OFN42_n_logic0),
	.I(FE_OFN38_n_logic0));
   BUF1S FE_OFC41_n_logic0 (.O(FE_OFN41_n_logic0),
	.I(FE_OFN37_n_logic0));
   BUF1 FE_OFC40_n_logic0 (.O(FE_OFN40_n_logic0),
	.I(FE_OFN36_n_logic0));
   BUF1S FE_OFC39_n_logic0 (.O(FE_OFN39_n_logic0),
	.I(FE_OFN35_n_logic0));
   BUF1S FE_OFC38_n_logic0 (.O(FE_OFN38_n_logic0),
	.I(FE_OFN34_n_logic0));
   INV1S FE_OFC37_n_logic0 (.O(FE_OFN37_n_logic0),
	.I(FE_OFN33_n_logic0));
   INV1S FE_OFC36_n_logic0 (.O(FE_OFN36_n_logic0),
	.I(FE_OFN33_n_logic0));
   BUF1S FE_OFC35_n_logic0 (.O(FE_OFN35_n_logic0),
	.I(n_logic0));
   BUF1S FE_OFC34_n_logic0 (.O(FE_OFN34_n_logic0),
	.I(n_logic0));
   INV1S FE_OFC33_n_logic0 (.O(FE_OFN33_n_logic0),
	.I(n_logic0));
   alu alu_in (.clk_p_i(i_clk_p_i),
	.reset_n_i(i_reset_n_i),
	.data_a_i(i_data_a_i),
	.data_b_i(i_data_b_i),
	.inst_i(i_inst_i),
	.data_o(i_data_o));
   TIE0 ipad_n_logic0 (.O(n_logic0));
   TIE1 ipad_n_logic1 (.O(n_logic1));
   XMD ipad_clk_p_i (.O(i_clk_p_i),
	.I(clk_p_i),
	.PU(FE_OFN46_n_logic0),
	.PD(FE_OFN46_n_logic0),
	.SMT(FE_OFN46_n_logic0));
   XMD ipad_reset_n_i (.O(i_reset_n_i),
	.I(reset_n_i),
	.PU(FE_OFN42_n_logic0),
	.PD(FE_OFN42_n_logic0),
	.SMT(FE_OFN42_n_logic0));
   XMD ipad_inst_i_0 (.O(i_inst_i[0]),
	.I(inst_i[0]),
	.PU(FE_OFN42_n_logic0),
	.PD(FE_OFN42_n_logic0),
	.SMT(FE_OFN38_n_logic0));
   XMD ipad_inst_i_1 (.O(i_inst_i[1]),
	.I(inst_i[1]),
	.PU(FE_OFN38_n_logic0),
	.PD(FE_OFN38_n_logic0),
	.SMT(FE_OFN38_n_logic0));
   XMD ipad_inst_i_2 (.O(i_inst_i[2]),
	.I(inst_i[2]),
	.PU(FE_OFN34_n_logic0),
	.PD(FE_OFN38_n_logic0),
	.SMT(FE_OFN34_n_logic0));
   XMD ipad_data_a_i_0 (.O(i_data_a_i[0]),
	.I(data_a_i[0]),
	.PU(n_logic0),
	.PD(FE_OFN34_n_logic0),
	.SMT(n_logic0));
   XMD ipad_data_a_i_1 (.O(i_data_a_i[1]),
	.I(data_a_i[1]),
	.PU(FE_OFN35_n_logic0),
	.PD(n_logic0),
	.SMT(FE_OFN35_n_logic0));
   XMD ipad_data_a_i_2 (.O(i_data_a_i[2]),
	.I(data_a_i[2]),
	.PU(FE_OFN35_n_logic0),
	.PD(FE_OFN35_n_logic0),
	.SMT(FE_OFN35_n_logic0));
   XMD ipad_data_a_i_3 (.O(i_data_a_i[3]),
	.I(data_a_i[3]),
	.PU(FE_OFN39_n_logic0),
	.PD(FE_OFN39_n_logic0),
	.SMT(FE_OFN39_n_logic0));
   XMD ipad_data_a_i_4 (.O(i_data_a_i[4]),
	.I(data_a_i[4]),
	.PU(FE_OFN39_n_logic0),
	.PD(FE_OFN39_n_logic0),
	.SMT(FE_OFN43_n_logic0));
   XMD ipad_data_a_i_5 (.O(i_data_a_i[5]),
	.I(data_a_i[5]),
	.PU(FE_OFN49_n_logic0),
	.PD(FE_OFN49_n_logic0),
	.SMT(FE_OFN49_n_logic0));
   XMD ipad_data_a_i_6 (.O(i_data_a_i[6]),
	.I(data_a_i[6]),
	.PU(FE_OFN53_n_logic0),
	.PD(FE_OFN49_n_logic0),
	.SMT(FE_OFN53_n_logic0));
   XMD ipad_data_a_i_7 (.O(i_data_a_i[7]),
	.I(data_a_i[7]),
	.PU(FE_OFN53_n_logic0),
	.PD(FE_OFN53_n_logic0),
	.SMT(FE_OFN53_n_logic0));
   XMD ipad_data_b_i_0 (.O(i_data_b_i[0]),
	.I(data_b_i[0]),
	.PU(FE_OFN57_n_logic0),
	.PD(FE_OFN57_n_logic0),
	.SMT(FE_OFN57_n_logic0));
   XMD ipad_data_b_i_1 (.O(i_data_b_i[1]),
	.I(data_b_i[1]),
	.PU(FE_OFN57_n_logic0),
	.PD(FE_OFN57_n_logic0),
	.SMT(FE_OFN57_n_logic0));
   XMD ipad_data_b_i_2 (.O(i_data_b_i[2]),
	.I(data_b_i[2]),
	.PU(FE_OFN58_n_logic0),
	.PD(FE_OFN58_n_logic0),
	.SMT(FE_OFN58_n_logic0));
   XMD ipad_data_b_i_3 (.O(i_data_b_i[3]),
	.I(data_b_i[3]),
	.PU(FE_OFN58_n_logic0),
	.PD(FE_OFN58_n_logic0),
	.SMT(FE_OFN58_n_logic0));
   XMD ipad_data_b_i_4 (.O(i_data_b_i[4]),
	.I(data_b_i[4]),
	.PU(FE_OFN54_n_logic0),
	.PD(FE_OFN54_n_logic0),
	.SMT(FE_OFN54_n_logic0));
   XMD ipad_data_b_i_5 (.O(i_data_b_i[5]),
	.I(data_b_i[5]),
	.PU(FE_OFN54_n_logic0),
	.PD(FE_OFN54_n_logic0),
	.SMT(FE_OFN50_n_logic0));
   XMD ipad_data_b_i_6 (.O(i_data_b_i[6]),
	.I(data_b_i[6]),
	.PU(FE_OFN50_n_logic0),
	.PD(FE_OFN50_n_logic0),
	.SMT(FE_OFN50_n_logic0));
   XMD ipad_data_b_i_7 (.O(i_data_b_i[7]),
	.I(data_b_i[7]),
	.PU(FE_OFN46_n_logic0),
	.PD(FE_OFN50_n_logic0),
	.SMT(FE_OFN46_n_logic0));
   YA2GSD ipad_data_o_0 (.O(data_o[0]),
	.I(i_data_o[0]),
	.E(FE_OFN62_n_logic1),
	.E2(FE_OFN49_n_logic0),
	.E4(FE_OFN45_n_logic0),
	.E8(FE_OFN45_n_logic0),
	.SR(FE_OFN45_n_logic0));
   YA2GSD ipad_data_o_1 (.O(data_o[1]),
	.I(i_data_o[1]),
	.E(FE_OFN62_n_logic1),
	.E2(FE_OFN45_n_logic0),
	.E4(FE_OFN41_n_logic0),
	.E8(FE_OFN45_n_logic0),
	.SR(FE_OFN41_n_logic0));
   YA2GSD ipad_data_o_2 (.O(data_o[2]),
	.I(i_data_o[2]),
	.E(FE_OFN62_n_logic1),
	.E2(FE_OFN41_n_logic0),
	.E4(FE_OFN41_n_logic0),
	.E8(FE_OFN41_n_logic0),
	.SR(FE_OFN37_n_logic0));
   YA2GSD ipad_data_o_3 (.O(data_o[3]),
	.I(i_data_o[3]),
	.E(FE_OFN62_n_logic1),
	.E2(FE_OFN37_n_logic0),
	.E4(FE_OFN37_n_logic0),
	.E8(FE_OFN37_n_logic0),
	.SR(FE_OFN37_n_logic0));
   YA2GSD ipad_data_o_4 (.O(data_o[4]),
	.I(i_data_o[4]),
	.E(FE_OFN62_n_logic1),
	.E2(FE_OFN36_n_logic0),
	.E4(FE_OFN36_n_logic0),
	.E8(FE_OFN36_n_logic0),
	.SR(FE_OFN36_n_logic0));
   YA2GSD ipad_data_o_5 (.O(data_o[5]),
	.I(i_data_o[5]),
	.E(FE_OFN61_n_logic1),
	.E2(FE_OFN40_n_logic0),
	.E4(FE_OFN40_n_logic0),
	.E8(FE_OFN40_n_logic0),
	.SR(FE_OFN40_n_logic0));
   YA2GSD ipad_data_o_6 (.O(data_o[6]),
	.I(i_data_o[6]),
	.E(FE_OFN61_n_logic1),
	.E2(FE_OFN40_n_logic0),
	.E4(FE_OFN44_n_logic0),
	.E8(FE_OFN44_n_logic0),
	.SR(FE_OFN44_n_logic0));
   YA2GSD ipad_data_o_7 (.O(data_o[7]),
	.I(i_data_o[7]),
	.E(FE_OFN61_n_logic1),
	.E2(FE_OFN44_n_logic0),
	.E4(FE_OFN48_n_logic0),
	.E8(FE_OFN44_n_logic0),
	.SR(FE_OFN48_n_logic0));
   YA2GSD ipad_data_o_8 (.O(data_o[8]),
	.I(i_data_o[8]),
	.E(FE_OFN61_n_logic1),
	.E2(FE_OFN48_n_logic0),
	.E4(FE_OFN48_n_logic0),
	.E8(FE_OFN48_n_logic0),
	.SR(FE_OFN52_n_logic0));
   YA2GSD ipad_data_o_9 (.O(data_o[9]),
	.I(i_data_o[9]),
	.E(FE_OFN61_n_logic1),
	.E2(FE_OFN52_n_logic0),
	.E4(FE_OFN52_n_logic0),
	.E8(FE_OFN52_n_logic0),
	.SR(FE_OFN56_n_logic0));
   YA2GSD ipad_data_o_10 (.O(data_o[10]),
	.I(i_data_o[10]),
	.E(FE_OFN63_n_logic1),
	.E2(FE_OFN56_n_logic0),
	.E4(FE_OFN56_n_logic0),
	.E8(FE_OFN56_n_logic0),
	.SR(FE_OFN59_n_logic0));
   YA2GSD ipad_data_o_11 (.O(data_o[11]),
	.I(i_data_o[11]),
	.E(FE_OFN63_n_logic1),
	.E2(FE_OFN59_n_logic0),
	.E4(FE_OFN59_n_logic0),
	.E8(FE_OFN59_n_logic0),
	.SR(FE_OFN59_n_logic0));
   YA2GSD ipad_data_o_12 (.O(data_o[12]),
	.I(i_data_o[12]),
	.E(FE_OFN63_n_logic1),
	.E2(FE_OFN55_n_logic0),
	.E4(FE_OFN55_n_logic0),
	.E8(FE_OFN55_n_logic0),
	.SR(FE_OFN55_n_logic0));
   YA2GSD ipad_data_o_13 (.O(data_o[13]),
	.I(i_data_o[13]),
	.E(FE_OFN63_n_logic1),
	.E2(FE_OFN51_n_logic0),
	.E4(FE_OFN51_n_logic0),
	.E8(FE_OFN51_n_logic0),
	.SR(FE_OFN51_n_logic0));
   YA2GSD ipad_data_o_14 (.O(data_o[14]),
	.I(i_data_o[14]),
	.E(FE_OFN63_n_logic1),
	.E2(FE_OFN47_n_logic0),
	.E4(FE_OFN47_n_logic0),
	.E8(FE_OFN47_n_logic0),
	.SR(FE_OFN47_n_logic0));
   YA2GSD ipad_data_o_15 (.O(data_o[15]),
	.I(i_data_o[15]),
	.E(FE_OFN63_n_logic1),
	.E2(FE_OFN43_n_logic0),
	.E4(FE_OFN43_n_logic0),
	.E8(FE_OFN43_n_logic0),
	.SR(FE_OFN43_n_logic0));
endmodule

