/*
###############################################################
#  Generated by:      Cadence Encounter 10.13-s272_1
#  OS:                Linux i686(Host ID leopard)
#  Generated on:      Fri Apr  8 00:25:26 2016
#  Design:            CHIP
#  Command:           saveNetlist CHIP.v
###############################################################
*/
module alu_DW01_add_0 (
	A, 
	B, 
	CI, 
	SUM, 
	CO);
   input [8:0] A;
   input [8:0] B;
   input CI;
   output [8:0] SUM;
   output CO;

   // Internal wires
   wire n1;
   wire [8:1] carry;

   FA1S U1_7 (.S(SUM[7]), 
	.CO(SUM[8]), 
	.CI(carry[7]), 
	.B(B[7]), 
	.A(A[7]));
   FA1S U1_1 (.S(SUM[1]), 
	.CO(carry[2]), 
	.CI(n1), 
	.B(B[1]), 
	.A(A[1]));
   FA1S U1_2 (.S(SUM[2]), 
	.CO(carry[3]), 
	.CI(carry[2]), 
	.B(B[2]), 
	.A(A[2]));
   FA1S U1_3 (.S(SUM[3]), 
	.CO(carry[4]), 
	.CI(carry[3]), 
	.B(B[3]), 
	.A(A[3]));
   FA1S U1_4 (.S(SUM[4]), 
	.CO(carry[5]), 
	.CI(carry[4]), 
	.B(B[4]), 
	.A(A[4]));
   FA1S U1_5 (.S(SUM[5]), 
	.CO(carry[6]), 
	.CI(carry[5]), 
	.B(B[5]), 
	.A(A[5]));
   FA1S U1_6 (.S(SUM[6]), 
	.CO(carry[7]), 
	.CI(carry[6]), 
	.B(B[6]), 
	.A(A[6]));
   AN2 U1 (.O(n1), 
	.I2(A[0]), 
	.I1(B[0]));
   XOR2HS U2 (.O(SUM[0]), 
	.I2(A[0]), 
	.I1(B[0]));
endmodule

module alu_DW01_sub_0 (
	A, 
	B, 
	CI, 
	DIFF, 
	CO);
   input [8:0] A;
   input [8:0] B;
   input CI;
   output [8:0] DIFF;
   output CO;

   // Internal wires
   wire n1;
   wire n2;
   wire n3;
   wire n4;
   wire n5;
   wire n6;
   wire n7;
   wire n8;
   wire n9;
   wire [9:0] carry;

   FA1S U2_1 (.S(DIFF[1]), 
	.CO(carry[2]), 
	.CI(carry[1]), 
	.B(n8), 
	.A(A[1]));
   FA1S U2_2 (.S(DIFF[2]), 
	.CO(carry[3]), 
	.CI(carry[2]), 
	.B(n7), 
	.A(A[2]));
   FA1S U2_3 (.S(DIFF[3]), 
	.CO(carry[4]), 
	.CI(carry[3]), 
	.B(n6), 
	.A(A[3]));
   FA1S U2_4 (.S(DIFF[4]), 
	.CO(carry[5]), 
	.CI(carry[4]), 
	.B(n5), 
	.A(A[4]));
   FA1S U2_5 (.S(DIFF[5]), 
	.CO(carry[6]), 
	.CI(carry[5]), 
	.B(n4), 
	.A(A[5]));
   FA1S U2_6 (.S(DIFF[6]), 
	.CO(carry[7]), 
	.CI(carry[6]), 
	.B(n3), 
	.A(A[6]));
   FA1S U2_7 (.S(DIFF[7]), 
	.CO(carry[8]), 
	.CI(carry[7]), 
	.B(n2), 
	.A(A[7]));
   INV1S U1 (.O(n2), 
	.I(B[7]));
   INV1S U2 (.O(n9), 
	.I(B[0]));
   INV1S U3 (.O(n3), 
	.I(B[6]));
   INV1S U4 (.O(n4), 
	.I(B[5]));
   INV1S U5 (.O(n5), 
	.I(B[4]));
   INV1S U6 (.O(n6), 
	.I(B[3]));
   INV1S U7 (.O(n7), 
	.I(B[2]));
   INV1S U8 (.O(n8), 
	.I(B[1]));
   INV1S U9 (.O(n1), 
	.I(A[0]));
   XNR2HS U10 (.O(DIFF[0]), 
	.I2(A[0]), 
	.I1(n9));
   ND2 U11 (.O(carry[1]), 
	.I2(n1), 
	.I1(B[0]));
   INV1S U12 (.O(DIFF[8]), 
	.I(carry[8]));
endmodule

module alu_DW_mult_uns_0 (
	a, 
	b, 
	product);
   input [7:0] a;
   input [7:0] b;
   output [15:0] product;

   // Internal wires
   wire n2;
   wire n3;
   wire n4;
   wire n5;
   wire n6;
   wire n7;
   wire n8;
   wire n9;
   wire n10;
   wire n11;
   wire n12;
   wire n13;
   wire n14;
   wire n15;
   wire n16;
   wire n17;
   wire n18;
   wire n19;
   wire n20;
   wire n21;
   wire n22;
   wire n23;
   wire n24;
   wire n25;
   wire n26;
   wire n27;
   wire n28;
   wire n29;
   wire n30;
   wire n31;
   wire n32;
   wire n33;
   wire n34;
   wire n35;
   wire n36;
   wire n37;
   wire n38;
   wire n39;
   wire n40;
   wire n41;
   wire n42;
   wire n43;
   wire n44;
   wire n45;
   wire n46;
   wire n47;
   wire n48;
   wire n49;
   wire n50;
   wire n51;
   wire n52;
   wire n53;
   wire n54;
   wire n55;
   wire n56;
   wire n57;
   wire n58;
   wire n59;
   wire n60;
   wire n61;
   wire n62;
   wire n63;
   wire n64;
   wire n65;
   wire n66;
   wire n67;
   wire n68;
   wire n69;
   wire n70;
   wire n71;
   wire n72;
   wire n73;
   wire n74;
   wire n75;
   wire n76;
   wire n77;
   wire n78;
   wire n79;
   wire n80;
   wire n81;
   wire n82;
   wire n83;
   wire n84;
   wire n85;
   wire n86;
   wire n87;
   wire n88;
   wire n89;
   wire n90;
   wire n91;
   wire n92;
   wire n93;
   wire n94;
   wire n95;
   wire n96;
   wire n97;
   wire n98;
   wire n99;
   wire n100;
   wire n101;
   wire n102;
   wire n103;
   wire n104;
   wire n105;
   wire n106;
   wire n107;
   wire n108;
   wire n109;
   wire n110;
   wire n111;
   wire n112;
   wire n113;
   wire n114;
   wire n115;
   wire n116;
   wire n117;
   wire n118;
   wire n119;
   wire n120;
   wire n121;
   wire n122;
   wire n123;
   wire n124;
   wire n125;
   wire n126;
   wire n127;
   wire n128;
   wire n129;
   wire n130;
   wire n131;
   wire n132;
   wire n133;
   wire n134;
   wire n135;
   wire n136;
   wire n137;
   wire n138;
   wire n139;
   wire n140;
   wire n141;
   wire n142;
   wire n143;
   wire n144;
   wire n145;
   wire n146;
   wire n147;
   wire n148;
   wire n149;
   wire n150;
   wire n151;
   wire n152;
   wire n153;
   wire n154;
   wire n155;
   wire n156;
   wire n157;
   wire n158;
   wire n159;
   wire n160;
   wire n161;
   wire n216;
   wire n218;
   wire n222;
   wire n224;
   wire n226;
   wire n228;
   wire n230;
   wire n232;
   wire n234;
   wire n236;
   wire n237;
   wire n239;
   wire n240;
   wire n242;
   wire n243;
   wire n247;

   FA1S U2 (.S(product[14]), 
	.CO(product[15]), 
	.CI(n2), 
	.B(n15), 
	.A(n99));
   FA1S U3 (.S(product[13]), 
	.CO(n2), 
	.CI(n3), 
	.B(n17), 
	.A(n16));
   FA1S U4 (.S(product[12]), 
	.CO(n3), 
	.CI(n4), 
	.B(n21), 
	.A(n18));
   FA1S U5 (.S(product[11]), 
	.CO(n4), 
	.CI(n5), 
	.B(n22), 
	.A(n27));
   FA1S U6 (.S(product[10]), 
	.CO(n5), 
	.CI(n6), 
	.B(n28), 
	.A(n35));
   FA1S U7 (.S(product[9]), 
	.CO(n6), 
	.CI(n7), 
	.B(n36), 
	.A(n45));
   FA1S U8 (.S(product[8]), 
	.CO(n7), 
	.CI(n8), 
	.B(n46), 
	.A(n57));
   FA1S U9 (.S(product[7]), 
	.CO(n8), 
	.CI(n9), 
	.B(n58), 
	.A(n69));
   FA1S U10 (.S(product[6]), 
	.CO(n9), 
	.CI(n10), 
	.B(n70), 
	.A(n79));
   FA1S U11 (.S(product[5]), 
	.CO(n10), 
	.CI(n11), 
	.B(n80), 
	.A(n87));
   FA1S U12 (.S(product[4]), 
	.CO(n11), 
	.CI(n12), 
	.B(n88), 
	.A(n93));
   FA1S U13 (.S(product[3]), 
	.CO(n12), 
	.CI(n94), 
	.B(n13), 
	.A(n96));
   FA1S U14 (.S(product[2]), 
	.CO(n13), 
	.CI(n98), 
	.B(n14), 
	.A(n146));
   HA1 U15 (.S(product[1]), 
	.C(n14), 
	.B(n161), 
	.A(n154));
   FA1S U16 (.S(n16), 
	.CO(n15), 
	.CI(n19), 
	.B(n100), 
	.A(n107));
   FA1S U17 (.S(n18), 
	.CO(n17), 
	.CI(n23), 
	.B(n20), 
	.A(n25));
   FA1S U18 (.S(n20), 
	.CO(n19), 
	.CI(n108), 
	.B(n101), 
	.A(n115));
   FA1S U19 (.S(n22), 
	.CO(n21), 
	.CI(n29), 
	.B(n24), 
	.A(n31));
   FA1S U20 (.S(n24), 
	.CO(n23), 
	.CI(n26), 
	.B(n33), 
	.A(n116));
   FA1S U21 (.S(n26), 
	.CO(n25), 
	.CI(n109), 
	.B(n102), 
	.A(n123));
   FA1S U22 (.S(n28), 
	.CO(n27), 
	.CI(n30), 
	.B(n37), 
	.A(n32));
   FA1S U23 (.S(n30), 
	.CO(n29), 
	.CI(n39), 
	.B(n34), 
	.A(n41));
   FA1S U24 (.S(n32), 
	.CO(n31), 
	.CI(n43), 
	.B(n117), 
	.A(n124));
   FA1S U25 (.S(n34), 
	.CO(n33), 
	.CI(n110), 
	.B(n103), 
	.A(n131));
   FA1S U26 (.S(n36), 
	.CO(n35), 
	.CI(n38), 
	.B(n47), 
	.A(n40));
   FA1S U27 (.S(n38), 
	.CO(n37), 
	.CI(n49), 
	.B(n51), 
	.A(n44));
   FA1S U28 (.S(n40), 
	.CO(n39), 
	.CI(n42), 
	.B(n53), 
	.A(n55));
   FA1S U29 (.S(n42), 
	.CO(n41), 
	.CI(n132), 
	.B(n125), 
	.A(n118));
   FA1S U30 (.S(n44), 
	.CO(n43), 
	.CI(n111), 
	.B(n104), 
	.A(n139));
   FA1S U31 (.S(n46), 
	.CO(n45), 
	.CI(n48), 
	.B(n59), 
	.A(n50));
   FA1S U32 (.S(n48), 
	.CO(n47), 
	.CI(n61), 
	.B(n52), 
	.A(n54));
   FA1S U33 (.S(n50), 
	.CO(n49), 
	.CI(n63), 
	.B(n65), 
	.A(n56));
   FA1S U34 (.S(n52), 
	.CO(n51), 
	.CI(n67), 
	.B(n133), 
	.A(n140));
   FA1S U35 (.S(n54), 
	.CO(n53), 
	.CI(n147), 
	.B(n119), 
	.A(n126));
   HA1 U36 (.S(n56), 
	.C(n55), 
	.B(n105), 
	.A(n112));
   FA1S U37 (.S(n58), 
	.CO(n57), 
	.CI(n60), 
	.B(n62), 
	.A(n71));
   FA1S U38 (.S(n60), 
	.CO(n59), 
	.CI(n73), 
	.B(n66), 
	.A(n64));
   FA1S U39 (.S(n62), 
	.CO(n61), 
	.CI(n75), 
	.B(n68), 
	.A(n77));
   FA1S U40 (.S(n64), 
	.CO(n63), 
	.CI(n134), 
	.B(n127), 
	.A(n141));
   FA1S U41 (.S(n66), 
	.CO(n65), 
	.CI(n148), 
	.B(n120), 
	.A(n155));
   HA1 U42 (.S(n68), 
	.C(n67), 
	.B(n106), 
	.A(n113));
   FA1S U43 (.S(n70), 
	.CO(n69), 
	.CI(n72), 
	.B(n74), 
	.A(n81));
   FA1S U44 (.S(n72), 
	.CO(n71), 
	.CI(n76), 
	.B(n83), 
	.A(n78));
   FA1S U45 (.S(n74), 
	.CO(n73), 
	.CI(n85), 
	.B(n135), 
	.A(n142));
   FA1S U46 (.S(n76), 
	.CO(n75), 
	.CI(n149), 
	.B(n128), 
	.A(n156));
   HA1 U47 (.S(n78), 
	.C(n77), 
	.B(n114), 
	.A(n121));
   FA1S U48 (.S(n80), 
	.CO(n79), 
	.CI(n82), 
	.B(n84), 
	.A(n89));
   FA1S U49 (.S(n82), 
	.CO(n81), 
	.CI(n86), 
	.B(n91), 
	.A(n150));
   FA1S U50 (.S(n84), 
	.CO(n83), 
	.CI(n143), 
	.B(n136), 
	.A(n157));
   HA1 U51 (.S(n86), 
	.C(n85), 
	.B(n122), 
	.A(n129));
   FA1S U52 (.S(n88), 
	.CO(n87), 
	.CI(n90), 
	.B(n92), 
	.A(n95));
   FA1S U53 (.S(n90), 
	.CO(n89), 
	.CI(n151), 
	.B(n144), 
	.A(n158));
   HA1 U54 (.S(n92), 
	.C(n91), 
	.B(n130), 
	.A(n137));
   FA1S U55 (.S(n94), 
	.CO(n93), 
	.CI(n97), 
	.B(n152), 
	.A(n159));
   HA1 U56 (.S(n96), 
	.C(n95), 
	.B(n138), 
	.A(n145));
   HA1 U57 (.S(n98), 
	.C(n97), 
	.B(n153), 
	.A(n160));
   INV1S U142 (.O(n216), 
	.I(b[2]));
   INV1S U144 (.O(n218), 
	.I(a[1]));
   INV1S U148 (.O(n222), 
	.I(a[7]));
   INV1S U150 (.O(n224), 
	.I(b[5]));
   INV1S U152 (.O(n226), 
	.I(b[6]));
   INV1S U154 (.O(n228), 
	.I(b[4]));
   INV1S U156 (.O(n230), 
	.I(b[3]));
   INV1S U158 (.O(n232), 
	.I(b[1]));
   INV1S U160 (.O(n234), 
	.I(b[7]));
   INV1S U162 (.O(n236), 
	.I(a[4]));
   INV1S U163 (.O(n237), 
	.I(a[3]));
   INV1S U165 (.O(n239), 
	.I(a[5]));
   INV1S U166 (.O(n240), 
	.I(a[6]));
   INV1S U168 (.O(n242), 
	.I(a[2]));
   INV1S U169 (.O(n247), 
	.I(a[0]));
   INV1S U170 (.O(n243), 
	.I(b[0]));
   NR2 U174 (.O(product[0]), 
	.I2(n243), 
	.I1(n247));
   NR2 U175 (.O(n99), 
	.I2(n234), 
	.I1(n222));
   NR2 U176 (.O(n161), 
	.I2(n232), 
	.I1(n247));
   NR2 U177 (.O(n160), 
	.I2(n216), 
	.I1(n247));
   NR2 U178 (.O(n159), 
	.I2(n230), 
	.I1(n247));
   NR2 U179 (.O(n158), 
	.I2(n228), 
	.I1(n247));
   NR2 U180 (.O(n157), 
	.I2(n224), 
	.I1(n247));
   NR2 U181 (.O(n156), 
	.I2(n226), 
	.I1(n247));
   NR2 U182 (.O(n155), 
	.I2(n234), 
	.I1(n247));
   NR2 U183 (.O(n154), 
	.I2(n218), 
	.I1(n243));
   NR2 U184 (.O(n153), 
	.I2(n218), 
	.I1(n232));
   NR2 U185 (.O(n152), 
	.I2(n218), 
	.I1(n216));
   NR2 U186 (.O(n151), 
	.I2(n218), 
	.I1(n230));
   NR2 U187 (.O(n150), 
	.I2(n218), 
	.I1(n228));
   NR2 U188 (.O(n149), 
	.I2(n218), 
	.I1(n224));
   NR2 U189 (.O(n148), 
	.I2(n218), 
	.I1(n226));
   NR2 U190 (.O(n147), 
	.I2(n218), 
	.I1(n234));
   NR2 U191 (.O(n146), 
	.I2(n242), 
	.I1(n243));
   NR2 U192 (.O(n145), 
	.I2(n242), 
	.I1(n232));
   NR2 U193 (.O(n144), 
	.I2(n242), 
	.I1(n216));
   NR2 U194 (.O(n143), 
	.I2(n242), 
	.I1(n230));
   NR2 U195 (.O(n142), 
	.I2(n242), 
	.I1(n228));
   NR2 U196 (.O(n141), 
	.I2(n242), 
	.I1(n224));
   NR2 U197 (.O(n140), 
	.I2(n242), 
	.I1(n226));
   NR2 U198 (.O(n139), 
	.I2(n242), 
	.I1(n234));
   NR2 U199 (.O(n138), 
	.I2(n237), 
	.I1(n243));
   NR2 U200 (.O(n137), 
	.I2(n237), 
	.I1(n232));
   NR2 U201 (.O(n136), 
	.I2(n237), 
	.I1(n216));
   NR2 U202 (.O(n135), 
	.I2(n237), 
	.I1(n230));
   NR2 U203 (.O(n134), 
	.I2(n237), 
	.I1(n228));
   NR2 U204 (.O(n133), 
	.I2(n237), 
	.I1(n224));
   NR2 U205 (.O(n132), 
	.I2(n237), 
	.I1(n226));
   NR2 U206 (.O(n131), 
	.I2(n237), 
	.I1(n234));
   NR2 U207 (.O(n130), 
	.I2(n236), 
	.I1(n243));
   NR2 U208 (.O(n129), 
	.I2(n236), 
	.I1(n232));
   NR2 U209 (.O(n128), 
	.I2(n236), 
	.I1(n216));
   NR2 U210 (.O(n127), 
	.I2(n236), 
	.I1(n230));
   NR2 U211 (.O(n126), 
	.I2(n236), 
	.I1(n228));
   NR2 U212 (.O(n125), 
	.I2(n236), 
	.I1(n224));
   NR2 U213 (.O(n124), 
	.I2(n236), 
	.I1(n226));
   NR2 U214 (.O(n123), 
	.I2(n236), 
	.I1(n234));
   NR2 U215 (.O(n122), 
	.I2(n239), 
	.I1(n243));
   NR2 U216 (.O(n121), 
	.I2(n239), 
	.I1(n232));
   NR2 U217 (.O(n120), 
	.I2(n239), 
	.I1(n216));
   NR2 U218 (.O(n119), 
	.I2(n239), 
	.I1(n230));
   NR2 U219 (.O(n118), 
	.I2(n239), 
	.I1(n228));
   NR2 U220 (.O(n117), 
	.I2(n239), 
	.I1(n224));
   NR2 U221 (.O(n116), 
	.I2(n239), 
	.I1(n226));
   NR2 U222 (.O(n115), 
	.I2(n239), 
	.I1(n234));
   NR2 U223 (.O(n114), 
	.I2(n240), 
	.I1(n243));
   NR2 U224 (.O(n113), 
	.I2(n240), 
	.I1(n232));
   NR2 U225 (.O(n112), 
	.I2(n240), 
	.I1(n216));
   NR2 U226 (.O(n111), 
	.I2(n240), 
	.I1(n230));
   NR2 U227 (.O(n110), 
	.I2(n240), 
	.I1(n228));
   NR2 U228 (.O(n109), 
	.I2(n240), 
	.I1(n224));
   NR2 U229 (.O(n108), 
	.I2(n240), 
	.I1(n226));
   NR2 U230 (.O(n107), 
	.I2(n240), 
	.I1(n234));
   NR2 U231 (.O(n106), 
	.I2(n222), 
	.I1(n243));
   NR2 U232 (.O(n105), 
	.I2(n232), 
	.I1(n222));
   NR2 U233 (.O(n104), 
	.I2(n216), 
	.I1(n222));
   NR2 U234 (.O(n103), 
	.I2(n230), 
	.I1(n222));
   NR2 U235 (.O(n102), 
	.I2(n228), 
	.I1(n222));
   NR2 U236 (.O(n101), 
	.I2(n224), 
	.I1(n222));
   NR2 U237 (.O(n100), 
	.I2(n226), 
	.I1(n222));
endmodule

module alu (
	clk_p_i, 
	reset_n_i, 
	data_a_i, 
	data_b_i, 
	inst_i, 
	data_o, 
	i_clk_p_i__L1_N1);
   input clk_p_i;
   input reset_n_i;
   input [7:0] data_a_i;
   input [7:0] data_b_i;
   input [2:0] inst_i;
   output [15:0] data_o;
   input i_clk_p_i__L1_N1;

   // Internal wires
   wire FE_UNCONNECTED_1;
   wire \reg_data_a[0] ;
   wire out_inst_1_15;
   wire N33;
   wire N34;
   wire N35;
   wire N36;
   wire N37;
   wire N38;
   wire N39;
   wire N40;
   wire n24;
   wire n25;
   wire n26;
   wire n27;
   wire n28;
   wire n29;
   wire n30;
   wire n31;
   wire n32;
   wire n33;
   wire n34;
   wire n35;
   wire n36;
   wire n37;
   wire n38;
   wire n39;
   wire n40;
   wire n41;
   wire n43;
   wire n44;
   wire n45;
   wire n46;
   wire n47;
   wire n48;
   wire n49;
   wire n50;
   wire n51;
   wire n52;
   wire n53;
   wire n54;
   wire n55;
   wire n56;
   wire n57;
   wire n58;
   wire n59;
   wire n60;
   wire n61;
   wire n62;
   wire n63;
   wire n64;
   wire n65;
   wire n66;
   wire n67;
   wire n68;
   wire n69;
   wire n70;
   wire n71;
   wire n72;
   wire n73;
   wire n74;
   wire n75;
   wire n76;
   wire n77;
   wire n78;
   wire n79;
   wire n80;
   wire n81;
   wire n82;
   wire \add_51/carry[2] ;
   wire \add_51/carry[3] ;
   wire \add_51/carry[4] ;
   wire \add_51/carry[5] ;
   wire \add_51/carry[6] ;
   wire \add_51/carry[7] ;
   wire \add_51/carry[8] ;
   wire \add_51/A[0] ;
   wire \add_51/A[1] ;
   wire \add_51/A[2] ;
   wire \add_51/A[3] ;
   wire \add_51/A[4] ;
   wire \add_51/A[5] ;
   wire \add_51/A[6] ;
   wire \add_51/A[7] ;
   wire n84;
   wire n87;
   wire n88;
   wire n89;
   wire n91;
   wire n93;
   wire n95;
   wire n102;
   wire n103;
   wire n106;
   wire n108;
   wire n110;
   wire n111;
   wire [15:0] ALU_d2_w;
   wire [7:0] reg_data_b;
   wire [8:0] out_inst_0;
   wire [7:0] out_inst_1;
   wire [15:0] out_inst_2;
   wire [6:0] out_inst_3;
   wire [2:0] reg_inst;
   wire [2:0] inst_i_v;

   OA222 U76 (.O(n31), 
	.C2(n37), 
	.C1(n36), 
	.B2(n35), 
	.B1(n34), 
	.A2(n33), 
	.A1(n32));
   ND2 U77 (.O(n25), 
	.I2(n103), 
	.I1(inst_i[0]));
   ND2 U78 (.O(ALU_d2_w[9]), 
	.I2(n41), 
	.I1(n40));
   ND2 U79 (.O(n43), 
	.I2(n39), 
	.I1(out_inst_0[8]));
   AO112 U80 (.O(ALU_d2_w[7]), 
	.C2(n39), 
	.C1(out_inst_0[7]), 
	.B1(n46), 
	.A1(n45));
   AO222 U81 (.O(n46), 
	.C2(n48), 
	.C1(n87), 
	.B2(n93), 
	.B1(N39), 
	.A2(out_inst_1[7]), 
	.A1(n47));
   OR3B2 U82 (.O(ALU_d2_w[6]), 
	.I1(n49), 
	.B2(n51), 
	.B1(n50));
   AO222 U83 (.O(n49), 
	.C2(n39), 
	.C1(out_inst_0[6]), 
	.B2(n84), 
	.B1(out_inst_3[6]), 
	.A2(n91), 
	.A1(out_inst_2[6]));
   OR3B2 U84 (.O(ALU_d2_w[5]), 
	.I1(n53), 
	.B2(n55), 
	.B1(n54));
   AO222 U85 (.O(n53), 
	.C2(n39), 
	.C1(out_inst_0[5]), 
	.B2(n84), 
	.B1(out_inst_3[5]), 
	.A2(n91), 
	.A1(out_inst_2[5]));
   OR3B2 U86 (.O(ALU_d2_w[4]), 
	.I1(n57), 
	.B2(n59), 
	.B1(n58));
   AO222 U87 (.O(n57), 
	.C2(n39), 
	.C1(out_inst_0[4]), 
	.B2(n84), 
	.B1(out_inst_3[4]), 
	.A2(n91), 
	.A1(out_inst_2[4]));
   OR3B2 U88 (.O(ALU_d2_w[3]), 
	.I1(n61), 
	.B2(n63), 
	.B1(n62));
   AO222 U89 (.O(n61), 
	.C2(n39), 
	.C1(out_inst_0[3]), 
	.B2(n84), 
	.B1(out_inst_3[3]), 
	.A2(n91), 
	.A1(out_inst_2[3]));
   OR3B2 U90 (.O(ALU_d2_w[2]), 
	.I1(n65), 
	.B2(n67), 
	.B1(n66));
   AO222 U91 (.O(n65), 
	.C2(n39), 
	.C1(out_inst_0[2]), 
	.B2(n84), 
	.B1(out_inst_3[2]), 
	.A2(n91), 
	.A1(out_inst_2[2]));
   OR3B2 U92 (.O(ALU_d2_w[1]), 
	.I1(n69), 
	.B2(n71), 
	.B1(n70));
   AO222 U93 (.O(n69), 
	.C2(n39), 
	.C1(out_inst_0[1]), 
	.B2(n84), 
	.B1(out_inst_3[1]), 
	.A2(n91), 
	.A1(out_inst_2[1]));
   ND2 U94 (.O(ALU_d2_w[15]), 
	.I2(n41), 
	.I1(n73));
   ND2 U95 (.O(ALU_d2_w[14]), 
	.I2(n41), 
	.I1(n74));
   ND2 U96 (.O(ALU_d2_w[13]), 
	.I2(n41), 
	.I1(n75));
   ND2 U97 (.O(ALU_d2_w[12]), 
	.I2(n41), 
	.I1(n76));
   ND2 U98 (.O(ALU_d2_w[11]), 
	.I2(n41), 
	.I1(n77));
   ND2 U99 (.O(ALU_d2_w[10]), 
	.I2(n41), 
	.I1(n78));
   OR3B2 U100 (.O(ALU_d2_w[0]), 
	.I1(n80), 
	.B2(n82), 
	.B1(n81));
   AO222 U101 (.O(n80), 
	.C2(n39), 
	.C1(out_inst_0[0]), 
	.B2(n84), 
	.B1(out_inst_3[0]), 
	.A2(n91), 
	.A1(out_inst_2[0]));
   alu_DW01_add_0 add_43 (.A({ FE_UNCONNECTED_1,
		out_inst_3,
		\reg_data_a[0]  }), 
	.B({ FE_UNCONNECTED_1,
		reg_data_b }), 
	.CI(FE_UNCONNECTED_1), 
	.SUM(out_inst_0));
   alu_DW01_sub_0 r306 (.A({ FE_UNCONNECTED_1,
		reg_data_b }), 
	.B({ FE_UNCONNECTED_1,
		out_inst_3,
		\reg_data_a[0]  }), 
	.CI(FE_UNCONNECTED_1), 
	.DIFF({ out_inst_1_15,
		out_inst_1 }));
   alu_DW_mult_uns_0 mult_45 (.a({ out_inst_3,
		\reg_data_a[0]  }), 
	.b(reg_data_b), 
	.product(out_inst_2));
   HA1 \add_51/U1_1_1  (.S(N33), 
	.C(\add_51/carry[2] ), 
	.B(\add_51/A[0] ), 
	.A(\add_51/A[1] ));
   HA1 \add_51/U1_1_2  (.S(N34), 
	.C(\add_51/carry[3] ), 
	.B(\add_51/carry[2] ), 
	.A(\add_51/A[2] ));
   HA1 \add_51/U1_1_3  (.S(N35), 
	.C(\add_51/carry[4] ), 
	.B(\add_51/carry[3] ), 
	.A(\add_51/A[3] ));
   HA1 \add_51/U1_1_4  (.S(N36), 
	.C(\add_51/carry[5] ), 
	.B(\add_51/carry[4] ), 
	.A(\add_51/A[4] ));
   HA1 \add_51/U1_1_5  (.S(N37), 
	.C(\add_51/carry[6] ), 
	.B(\add_51/carry[5] ), 
	.A(\add_51/A[5] ));
   HA1 \add_51/U1_1_6  (.S(N38), 
	.C(\add_51/carry[7] ), 
	.B(\add_51/carry[6] ), 
	.A(\add_51/A[6] ));
   HA1 \add_51/U1_1_7  (.S(N39), 
	.C(\add_51/carry[8] ), 
	.B(\add_51/carry[7] ), 
	.A(\add_51/A[7] ));
   QDFFRBN \reg_inst_reg[0]  (.RB(reset_n_i), 
	.Q(reg_inst[0]), 
	.D(inst_i_v[0]), 
	.CK(i_clk_p_i__L1_N1));
   QDFFRBN \reg_inst_reg[2]  (.RB(reset_n_i), 
	.Q(reg_inst[2]), 
	.D(inst_i_v[2]), 
	.CK(i_clk_p_i__L1_N1));
   QDFFRBN \reg_inst_reg[1]  (.RB(reset_n_i), 
	.Q(reg_inst[1]), 
	.D(inst_i_v[1]), 
	.CK(i_clk_p_i__L1_N1));
   QDFFRBN \reg_data_b_reg[7]  (.RB(reset_n_i), 
	.Q(reg_data_b[7]), 
	.D(data_b_i[7]), 
	.CK(i_clk_p_i__L1_N1));
   QDFFRBN \reg_data_b_reg[6]  (.RB(reset_n_i), 
	.Q(reg_data_b[6]), 
	.D(data_b_i[6]), 
	.CK(i_clk_p_i__L1_N1));
   QDFFRBN \reg_data_b_reg[5]  (.RB(reset_n_i), 
	.Q(reg_data_b[5]), 
	.D(data_b_i[5]), 
	.CK(i_clk_p_i__L1_N1));
   QDFFRBN \reg_data_b_reg[4]  (.RB(reset_n_i), 
	.Q(reg_data_b[4]), 
	.D(data_b_i[4]), 
	.CK(i_clk_p_i__L1_N1));
   QDFFRBN \reg_data_b_reg[3]  (.RB(reset_n_i), 
	.Q(reg_data_b[3]), 
	.D(data_b_i[3]), 
	.CK(i_clk_p_i__L1_N1));
   QDFFRBN \reg_data_b_reg[1]  (.RB(reset_n_i), 
	.Q(reg_data_b[1]), 
	.D(data_b_i[1]), 
	.CK(i_clk_p_i__L1_N1));
   QDFFRBN \reg_data_a_reg[7]  (.RB(reset_n_i), 
	.Q(out_inst_3[6]), 
	.D(data_a_i[7]), 
	.CK(i_clk_p_i__L1_N1));
   QDFFRBN \reg_data_a_reg[6]  (.RB(reset_n_i), 
	.Q(out_inst_3[5]), 
	.D(data_a_i[6]), 
	.CK(i_clk_p_i__L1_N1));
   QDFFRBN \reg_data_a_reg[5]  (.RB(reset_n_i), 
	.Q(out_inst_3[4]), 
	.D(data_a_i[5]), 
	.CK(i_clk_p_i__L1_N1));
   QDFFRBN \reg_data_a_reg[4]  (.RB(reset_n_i), 
	.Q(out_inst_3[3]), 
	.D(data_a_i[4]), 
	.CK(clk_p_i));
   QDFFRBN \reg_data_a_reg[3]  (.RB(reset_n_i), 
	.Q(out_inst_3[2]), 
	.D(data_a_i[3]), 
	.CK(clk_p_i));
   QDFFRBN \reg_data_a_reg[2]  (.RB(reset_n_i), 
	.Q(out_inst_3[1]), 
	.D(data_a_i[2]), 
	.CK(clk_p_i));
   QDFFRBN \reg_data_b_reg[0]  (.RB(reset_n_i), 
	.Q(reg_data_b[0]), 
	.D(data_b_i[0]), 
	.CK(i_clk_p_i__L1_N1));
   QDFFRBN \reg_data_b_reg[2]  (.RB(reset_n_i), 
	.Q(reg_data_b[2]), 
	.D(data_b_i[2]), 
	.CK(i_clk_p_i__L1_N1));
   QDFFRBN \reg_data_a_reg[1]  (.RB(reset_n_i), 
	.Q(out_inst_3[0]), 
	.D(data_a_i[1]), 
	.CK(clk_p_i));
   QDFFRBN \reg_data_a_reg[0]  (.RB(reset_n_i), 
	.Q(\reg_data_a[0] ), 
	.D(data_a_i[0]), 
	.CK(clk_p_i));
   QDFFRBT \ALU_d2_r_reg[1]  (.RB(reset_n_i), 
	.Q(data_o[1]), 
	.D(ALU_d2_w[1]), 
	.CK(i_clk_p_i__L1_N1));
   QDFFRBT \ALU_d2_r_reg[4]  (.RB(reset_n_i), 
	.Q(data_o[4]), 
	.D(ALU_d2_w[4]), 
	.CK(clk_p_i));
   QDFFRBT \ALU_d2_r_reg[2]  (.RB(reset_n_i), 
	.Q(data_o[2]), 
	.D(ALU_d2_w[2]), 
	.CK(i_clk_p_i__L1_N1));
   QDFFRBT \ALU_d2_r_reg[5]  (.RB(reset_n_i), 
	.Q(data_o[5]), 
	.D(ALU_d2_w[5]), 
	.CK(clk_p_i));
   QDFFRBT \ALU_d2_r_reg[8]  (.RB(reset_n_i), 
	.Q(data_o[8]), 
	.D(ALU_d2_w[8]), 
	.CK(clk_p_i));
   QDFFRBT \ALU_d2_r_reg[0]  (.RB(reset_n_i), 
	.Q(data_o[0]), 
	.D(ALU_d2_w[0]), 
	.CK(i_clk_p_i__L1_N1));
   QDFFRBT \ALU_d2_r_reg[6]  (.RB(reset_n_i), 
	.Q(data_o[6]), 
	.D(ALU_d2_w[6]), 
	.CK(clk_p_i));
   QDFFRBT \ALU_d2_r_reg[3]  (.RB(reset_n_i), 
	.Q(data_o[3]), 
	.D(ALU_d2_w[3]), 
	.CK(i_clk_p_i__L1_N1));
   QDFFRBT \ALU_d2_r_reg[9]  (.RB(reset_n_i), 
	.Q(data_o[9]), 
	.D(ALU_d2_w[9]), 
	.CK(clk_p_i));
   QDFFRBT \ALU_d2_r_reg[7]  (.RB(reset_n_i), 
	.Q(data_o[7]), 
	.D(ALU_d2_w[7]), 
	.CK(clk_p_i));
   QDFFRBT \ALU_d2_r_reg[10]  (.RB(reset_n_i), 
	.Q(data_o[10]), 
	.D(ALU_d2_w[10]), 
	.CK(clk_p_i));
   QDFFRBT \ALU_d2_r_reg[11]  (.RB(reset_n_i), 
	.Q(data_o[11]), 
	.D(ALU_d2_w[11]), 
	.CK(clk_p_i));
   QDFFRBT \ALU_d2_r_reg[12]  (.RB(reset_n_i), 
	.Q(data_o[12]), 
	.D(ALU_d2_w[12]), 
	.CK(clk_p_i));
   QDFFRBT \ALU_d2_r_reg[13]  (.RB(reset_n_i), 
	.Q(data_o[13]), 
	.D(ALU_d2_w[13]), 
	.CK(clk_p_i));
   QDFFRBT \ALU_d2_r_reg[15]  (.RB(reset_n_i), 
	.Q(data_o[15]), 
	.D(ALU_d2_w[15]), 
	.CK(clk_p_i));
   QDFFRBT \ALU_d2_r_reg[14]  (.RB(reset_n_i), 
	.Q(data_o[14]), 
	.D(ALU_d2_w[14]), 
	.CK(clk_p_i));
   INV1S U102 (.O(n84), 
	.I(n37));
   INV1S U105 (.O(n87), 
	.I(n35));
   INV1S U106 (.O(n88), 
	.I(n29));
   NR2 U107 (.O(n89), 
	.I2(out_inst_1_15), 
	.I1(\add_51/carry[8] ));
   INV1S U109 (.O(n91), 
	.I(n33));
   INV1S U111 (.O(n93), 
	.I(n95));
   AOI22S U113 (.O(n74), 
	.B2(n91), 
	.B1(out_inst_2[14]), 
	.A2(n93), 
	.A1(n89));
   AOI22S U114 (.O(n77), 
	.B2(n91), 
	.B1(out_inst_2[11]), 
	.A2(n93), 
	.A1(n89));
   AOI22S U115 (.O(n76), 
	.B2(n91), 
	.B1(out_inst_2[12]), 
	.A2(n93), 
	.A1(n89));
   AOI22S U116 (.O(n75), 
	.B2(n91), 
	.B1(out_inst_2[13]), 
	.A2(n93), 
	.A1(n89));
   AOI22S U117 (.O(n73), 
	.B2(n91), 
	.B1(out_inst_2[15]), 
	.A2(n93), 
	.A1(n89));
   INV1S U118 (.O(n102), 
	.I(out_inst_1_15));
   AOI22S U119 (.O(n78), 
	.B2(n91), 
	.B1(out_inst_2[10]), 
	.A2(n93), 
	.A1(n89));
   AOI22S U120 (.O(n40), 
	.B2(n91), 
	.B1(out_inst_2[9]), 
	.A2(n93), 
	.A1(n89));
   AOI22S U121 (.O(n41), 
	.B2(n88), 
	.B1(n102), 
	.A2(n108), 
	.A1(out_inst_1_15));
   OAI12HS U122 (.O(n47), 
	.B2(n26), 
	.B1(out_inst_1_15), 
	.A1(n79));
   OR2 U123 (.O(n95), 
	.I2(n102), 
	.I1(n26));
   ND3 U125 (.O(ALU_d2_w[8]), 
	.I3(n44), 
	.I2(n43), 
	.I1(n41));
   AOI22S U126 (.O(n44), 
	.B2(n91), 
	.B1(out_inst_2[8]), 
	.A2(n93), 
	.A1(N40));
   INV1S U127 (.O(\add_51/A[7] ), 
	.I(out_inst_1[7]));
   INV1S U128 (.O(\add_51/A[6] ), 
	.I(out_inst_1[6]));
   INV1S U129 (.O(\add_51/A[5] ), 
	.I(out_inst_1[5]));
   INV1S U130 (.O(\add_51/A[4] ), 
	.I(out_inst_1[4]));
   INV1S U131 (.O(\add_51/A[0] ), 
	.I(out_inst_1[0]));
   INV1S U132 (.O(\add_51/A[3] ), 
	.I(out_inst_1[3]));
   INV1S U133 (.O(\add_51/A[2] ), 
	.I(out_inst_1[2]));
   INV1S U134 (.O(\add_51/A[1] ), 
	.I(out_inst_1[1]));
   INV1S U139 (.O(n108), 
	.I(n79));
   MOAI1S U144 (.O(n45), 
	.B2(n91), 
	.B1(out_inst_2[7]), 
	.A2(n29), 
	.A1(out_inst_1[7]));
   XOR2HS U145 (.O(n48), 
	.I2(out_inst_3[6]), 
	.I1(reg_data_b[7]));
   MOAI1S U146 (.O(n24), 
	.B2(n28), 
	.B1(n27), 
	.A2(n26), 
	.A1(n25));
   ND3 U147 (.O(n28), 
	.I3(inst_i[2]), 
	.I2(inst_i[0]), 
	.I1(inst_i[1]));
   OAI112HS U148 (.O(n27), 
	.C2(n29), 
	.C1(n25), 
	.B1(n31), 
	.A1(n30));
   NR2 U149 (.O(n30), 
	.I2(n108), 
	.I1(n39));
   AOI22S U150 (.O(n51), 
	.B2(\add_51/A[6] ), 
	.B1(n88), 
	.A2(n52), 
	.A1(n87));
   AOI22S U151 (.O(n50), 
	.B2(out_inst_1[6]), 
	.B1(n47), 
	.A2(n93), 
	.A1(N38));
   AOI22S U152 (.O(n55), 
	.B2(\add_51/A[5] ), 
	.B1(n88), 
	.A2(n56), 
	.A1(n87));
   AOI22S U153 (.O(n54), 
	.B2(out_inst_1[5]), 
	.B1(n47), 
	.A2(n93), 
	.A1(N37));
   AOI22S U154 (.O(n59), 
	.B2(\add_51/A[4] ), 
	.B1(n88), 
	.A2(n60), 
	.A1(n87));
   AOI22S U155 (.O(n58), 
	.B2(out_inst_1[4]), 
	.B1(n47), 
	.A2(n93), 
	.A1(N36));
   AOI22S U156 (.O(n63), 
	.B2(\add_51/A[3] ), 
	.B1(n88), 
	.A2(n64), 
	.A1(n87));
   AOI22S U157 (.O(n62), 
	.B2(out_inst_1[3]), 
	.B1(n47), 
	.A2(n93), 
	.A1(N35));
   AOI22S U158 (.O(n67), 
	.B2(\add_51/A[2] ), 
	.B1(n88), 
	.A2(n68), 
	.A1(n87));
   AOI22S U159 (.O(n66), 
	.B2(out_inst_1[2]), 
	.B1(n47), 
	.A2(n93), 
	.A1(N34));
   AOI22S U160 (.O(n71), 
	.B2(\add_51/A[1] ), 
	.B1(n88), 
	.A2(n72), 
	.A1(n87));
   AOI22S U161 (.O(n70), 
	.B2(out_inst_1[1]), 
	.B1(n47), 
	.A2(n93), 
	.A1(N33));
   AOI22S U162 (.O(n82), 
	.B2(\add_51/A[0] ), 
	.B1(n88), 
	.A2(out_inst_0[0]), 
	.A1(n87));
   AOI22S U163 (.O(n81), 
	.B2(out_inst_1[0]), 
	.B1(n47), 
	.A2(n93), 
	.A1(out_inst_1[0]));
   NR2 U164 (.O(n38), 
	.I2(inst_i[2]), 
	.I1(inst_i[1]));
   MOAI1S U165 (.O(inst_i_v[1]), 
	.B2(inst_i[1]), 
	.B1(n24), 
	.A2(n111), 
	.A1(n24));
   MOAI1S U166 (.O(inst_i_v[2]), 
	.B2(inst_i[2]), 
	.B1(n24), 
	.A2(n110), 
	.A1(n24));
   MOAI1S U167 (.O(inst_i_v[0]), 
	.B2(inst_i[0]), 
	.B1(n24), 
	.A2(n106), 
	.A1(n24));
   NR2 U168 (.O(n32), 
	.I2(inst_i[0]), 
	.I1(n38));
   MAOI1 U169 (.O(n34), 
	.B2(inst_i[2]), 
	.B1(inst_i[0]), 
	.A2(n103), 
	.A1(inst_i[0]));
   AOI12HS U170 (.O(n36), 
	.B2(inst_i[2]), 
	.B1(inst_i[1]), 
	.A1(n38));
   INV1S U171 (.O(n103), 
	.I(inst_i[1]));
   NR3 U172 (.O(n39), 
	.I3(reg_inst[0]), 
	.I2(reg_inst[2]), 
	.I1(reg_inst[1]));
   INV1S U173 (.O(n110), 
	.I(reg_inst[2]));
   INV1S U174 (.O(n111), 
	.I(reg_inst[1]));
   INV1S U175 (.O(n106), 
	.I(reg_inst[0]));
   ND3 U176 (.O(n26), 
	.I3(reg_inst[1]), 
	.I2(n106), 
	.I1(reg_inst[2]));
   ND3 U177 (.O(n33), 
	.I3(reg_inst[1]), 
	.I2(n110), 
	.I1(n106));
   ND3 U178 (.O(n29), 
	.I3(reg_inst[2]), 
	.I2(n111), 
	.I1(n106));
   ND3 U179 (.O(n79), 
	.I3(reg_inst[0]), 
	.I2(n110), 
	.I1(n111));
   ND3 U180 (.O(n35), 
	.I3(reg_inst[2]), 
	.I2(n111), 
	.I1(reg_inst[0]));
   ND3 U181 (.O(n37), 
	.I3(reg_inst[1]), 
	.I2(n110), 
	.I1(reg_inst[0]));
   XOR2HS U183 (.O(n52), 
	.I2(out_inst_3[5]), 
	.I1(reg_data_b[6]));
   XOR2HS U184 (.O(n56), 
	.I2(out_inst_3[4]), 
	.I1(reg_data_b[5]));
   XOR2HS U185 (.O(n60), 
	.I2(out_inst_3[3]), 
	.I1(reg_data_b[4]));
   XOR2HS U186 (.O(n64), 
	.I2(out_inst_3[2]), 
	.I1(reg_data_b[3]));
   XOR2HS U187 (.O(n68), 
	.I2(out_inst_3[1]), 
	.I1(reg_data_b[2]));
   XOR2HS U188 (.O(n72), 
	.I2(out_inst_3[0]), 
	.I1(reg_data_b[1]));
   XOR2HS U192 (.O(N40), 
	.I2(n102), 
	.I1(\add_51/carry[8] ));
endmodule

module CHIP (
	clk_p_i, 
	reset_n_i, 
	data_a_i, 
	data_b_i, 
	inst_i, 
	data_o);
   input clk_p_i;
   input reset_n_i;
   input [7:0] data_a_i;
   input [7:0] data_b_i;
   input [2:0] inst_i;
   output [15:0] data_o;

   // Internal wires
   wire i_clk_p_i__L1_N1;
   wire i_clk_p_i__L1_N0;
   wire FE_OFN2_n_logic0;
   wire FE_OFN1_n_logic0;
   wire FE_OFN0_n_logic0;
   wire [7:0] i_data_a_i;
   wire [7:0] i_data_b_i;
   wire [2:0] i_inst_i;
   wire [15:0] i_data_o;
   wire i_clk_p_i;
   wire i_reset_n_i;
   wire n_logic0;
   wire n_logic1;

   BUF12CK i_clk_p_i__L1_I1 (.O(i_clk_p_i__L1_N1), 
	.I(i_clk_p_i));
   BUF12CK i_clk_p_i__L1_I0 (.O(i_clk_p_i__L1_N0), 
	.I(i_clk_p_i));
   BUF3 FE_OFC2_n_logic0 (.O(FE_OFN2_n_logic0), 
	.I(FE_OFN1_n_logic0));
   BUF2CK FE_OFC1_n_logic0 (.O(FE_OFN1_n_logic0), 
	.I(n_logic0));
   BUF2CK FE_OFC0_n_logic0 (.O(FE_OFN0_n_logic0), 
	.I(n_logic0));
   alu alu_in (.clk_p_i(i_clk_p_i__L1_N0), 
	.reset_n_i(i_reset_n_i), 
	.data_a_i(i_data_a_i), 
	.data_b_i(i_data_b_i), 
	.inst_i(i_inst_i), 
	.data_o(i_data_o), 
	.i_clk_p_i__L1_N1(i_clk_p_i__L1_N1));
   TIE0 ipad_n_logic0 (.O(n_logic0));
   TIE1 ipad_n_logic1 (.O(n_logic1));
   XMD ipad_clk_p_i (.SMT(n_logic0), 
	.PU(n_logic0), 
	.PD(n_logic0), 
	.O(i_clk_p_i), 
	.I(clk_p_i));
   XMD ipad_reset_n_i (.SMT(FE_OFN1_n_logic0), 
	.PU(FE_OFN1_n_logic0), 
	.PD(FE_OFN1_n_logic0), 
	.O(i_reset_n_i), 
	.I(reset_n_i));
   XMD ipad_inst_i_0 (.SMT(FE_OFN1_n_logic0), 
	.PU(FE_OFN1_n_logic0), 
	.PD(FE_OFN1_n_logic0), 
	.O(i_inst_i[0]), 
	.I(inst_i[0]));
   XMD ipad_inst_i_1 (.SMT(FE_OFN1_n_logic0), 
	.PU(FE_OFN1_n_logic0), 
	.PD(FE_OFN1_n_logic0), 
	.O(i_inst_i[1]), 
	.I(inst_i[1]));
   XMD ipad_inst_i_2 (.SMT(FE_OFN1_n_logic0), 
	.PU(FE_OFN1_n_logic0), 
	.PD(FE_OFN1_n_logic0), 
	.O(i_inst_i[2]), 
	.I(inst_i[2]));
   XMD ipad_data_a_i_0 (.SMT(FE_OFN1_n_logic0), 
	.PU(FE_OFN1_n_logic0), 
	.PD(FE_OFN1_n_logic0), 
	.O(i_data_a_i[0]), 
	.I(data_a_i[0]));
   XMD ipad_data_a_i_1 (.SMT(FE_OFN1_n_logic0), 
	.PU(FE_OFN1_n_logic0), 
	.PD(FE_OFN1_n_logic0), 
	.O(i_data_a_i[1]), 
	.I(data_a_i[1]));
   XMD ipad_data_a_i_2 (.SMT(FE_OFN1_n_logic0), 
	.PU(FE_OFN1_n_logic0), 
	.PD(FE_OFN1_n_logic0), 
	.O(i_data_a_i[2]), 
	.I(data_a_i[2]));
   XMD ipad_data_a_i_3 (.SMT(FE_OFN1_n_logic0), 
	.PU(FE_OFN1_n_logic0), 
	.PD(FE_OFN1_n_logic0), 
	.O(i_data_a_i[3]), 
	.I(data_a_i[3]));
   XMD ipad_data_a_i_4 (.SMT(FE_OFN1_n_logic0), 
	.PU(FE_OFN1_n_logic0), 
	.PD(FE_OFN1_n_logic0), 
	.O(i_data_a_i[4]), 
	.I(data_a_i[4]));
   XMD ipad_data_a_i_5 (.SMT(n_logic0), 
	.PU(n_logic0), 
	.PD(n_logic0), 
	.O(i_data_a_i[5]), 
	.I(data_a_i[5]));
   XMD ipad_data_a_i_6 (.SMT(n_logic0), 
	.PU(n_logic0), 
	.PD(n_logic0), 
	.O(i_data_a_i[6]), 
	.I(data_a_i[6]));
   XMD ipad_data_a_i_7 (.SMT(n_logic0), 
	.PU(n_logic0), 
	.PD(n_logic0), 
	.O(i_data_a_i[7]), 
	.I(data_a_i[7]));
   XMD ipad_data_b_i_0 (.SMT(n_logic0), 
	.PU(n_logic0), 
	.PD(n_logic0), 
	.O(i_data_b_i[0]), 
	.I(data_b_i[0]));
   XMD ipad_data_b_i_1 (.SMT(n_logic0), 
	.PU(n_logic0), 
	.PD(n_logic0), 
	.O(i_data_b_i[1]), 
	.I(data_b_i[1]));
   XMD ipad_data_b_i_2 (.SMT(n_logic0), 
	.PU(n_logic0), 
	.PD(n_logic0), 
	.O(i_data_b_i[2]), 
	.I(data_b_i[2]));
   XMD ipad_data_b_i_3 (.SMT(n_logic0), 
	.PU(n_logic0), 
	.PD(n_logic0), 
	.O(i_data_b_i[3]), 
	.I(data_b_i[3]));
   XMD ipad_data_b_i_4 (.SMT(n_logic0), 
	.PU(n_logic0), 
	.PD(n_logic0), 
	.O(i_data_b_i[4]), 
	.I(data_b_i[4]));
   XMD ipad_data_b_i_5 (.SMT(n_logic0), 
	.PU(n_logic0), 
	.PD(n_logic0), 
	.O(i_data_b_i[5]), 
	.I(data_b_i[5]));
   XMD ipad_data_b_i_6 (.SMT(n_logic0), 
	.PU(n_logic0), 
	.PD(n_logic0), 
	.O(i_data_b_i[6]), 
	.I(data_b_i[6]));
   XMD ipad_data_b_i_7 (.SMT(n_logic0), 
	.PU(n_logic0), 
	.PD(n_logic0), 
	.O(i_data_b_i[7]), 
	.I(data_b_i[7]));
   YA2GSD ipad_data_o_0 (.SR(FE_OFN0_n_logic0), 
	.O(data_o[0]), 
	.I(i_data_o[0]), 
	.E8(FE_OFN0_n_logic0), 
	.E4(FE_OFN0_n_logic0), 
	.E2(FE_OFN0_n_logic0), 
	.E(n_logic1));
   YA2GSD ipad_data_o_1 (.SR(FE_OFN0_n_logic0), 
	.O(data_o[1]), 
	.I(i_data_o[1]), 
	.E8(FE_OFN0_n_logic0), 
	.E4(FE_OFN0_n_logic0), 
	.E2(FE_OFN0_n_logic0), 
	.E(n_logic1));
   YA2GSD ipad_data_o_2 (.SR(FE_OFN0_n_logic0), 
	.O(data_o[2]), 
	.I(i_data_o[2]), 
	.E8(FE_OFN0_n_logic0), 
	.E4(FE_OFN0_n_logic0), 
	.E2(FE_OFN0_n_logic0), 
	.E(n_logic1));
   YA2GSD ipad_data_o_3 (.SR(FE_OFN0_n_logic0), 
	.O(data_o[3]), 
	.I(i_data_o[3]), 
	.E8(FE_OFN0_n_logic0), 
	.E4(FE_OFN0_n_logic0), 
	.E2(FE_OFN0_n_logic0), 
	.E(n_logic1));
   YA2GSD ipad_data_o_4 (.SR(FE_OFN0_n_logic0), 
	.O(data_o[4]), 
	.I(i_data_o[4]), 
	.E8(FE_OFN0_n_logic0), 
	.E4(FE_OFN0_n_logic0), 
	.E2(FE_OFN0_n_logic0), 
	.E(n_logic1));
   YA2GSD ipad_data_o_5 (.SR(FE_OFN0_n_logic0), 
	.O(data_o[5]), 
	.I(i_data_o[5]), 
	.E8(FE_OFN0_n_logic0), 
	.E4(FE_OFN0_n_logic0), 
	.E2(FE_OFN0_n_logic0), 
	.E(n_logic1));
   YA2GSD ipad_data_o_6 (.SR(FE_OFN0_n_logic0), 
	.O(data_o[6]), 
	.I(i_data_o[6]), 
	.E8(FE_OFN0_n_logic0), 
	.E4(FE_OFN0_n_logic0), 
	.E2(FE_OFN0_n_logic0), 
	.E(n_logic1));
   YA2GSD ipad_data_o_7 (.SR(FE_OFN2_n_logic0), 
	.O(data_o[7]), 
	.I(i_data_o[7]), 
	.E8(FE_OFN0_n_logic0), 
	.E4(FE_OFN0_n_logic0), 
	.E2(FE_OFN0_n_logic0), 
	.E(n_logic1));
   YA2GSD ipad_data_o_8 (.SR(FE_OFN2_n_logic0), 
	.O(data_o[8]), 
	.I(i_data_o[8]), 
	.E8(FE_OFN2_n_logic0), 
	.E4(FE_OFN2_n_logic0), 
	.E2(FE_OFN2_n_logic0), 
	.E(n_logic1));
   YA2GSD ipad_data_o_9 (.SR(FE_OFN2_n_logic0), 
	.O(data_o[9]), 
	.I(i_data_o[9]), 
	.E8(FE_OFN2_n_logic0), 
	.E4(FE_OFN2_n_logic0), 
	.E2(FE_OFN2_n_logic0), 
	.E(n_logic1));
   YA2GSD ipad_data_o_10 (.SR(FE_OFN2_n_logic0), 
	.O(data_o[10]), 
	.I(i_data_o[10]), 
	.E8(FE_OFN2_n_logic0), 
	.E4(FE_OFN2_n_logic0), 
	.E2(FE_OFN2_n_logic0), 
	.E(n_logic1));
   YA2GSD ipad_data_o_11 (.SR(FE_OFN2_n_logic0), 
	.O(data_o[11]), 
	.I(i_data_o[11]), 
	.E8(FE_OFN2_n_logic0), 
	.E4(FE_OFN2_n_logic0), 
	.E2(FE_OFN2_n_logic0), 
	.E(n_logic1));
   YA2GSD ipad_data_o_12 (.SR(FE_OFN2_n_logic0), 
	.O(data_o[12]), 
	.I(i_data_o[12]), 
	.E8(FE_OFN2_n_logic0), 
	.E4(FE_OFN2_n_logic0), 
	.E2(FE_OFN2_n_logic0), 
	.E(n_logic1));
   YA2GSD ipad_data_o_13 (.SR(FE_OFN2_n_logic0), 
	.O(data_o[13]), 
	.I(i_data_o[13]), 
	.E8(FE_OFN2_n_logic0), 
	.E4(FE_OFN2_n_logic0), 
	.E2(FE_OFN2_n_logic0), 
	.E(n_logic1));
   YA2GSD ipad_data_o_14 (.SR(FE_OFN1_n_logic0), 
	.O(data_o[14]), 
	.I(i_data_o[14]), 
	.E8(FE_OFN1_n_logic0), 
	.E4(FE_OFN1_n_logic0), 
	.E2(FE_OFN1_n_logic0), 
	.E(n_logic1));
   YA2GSD ipad_data_o_15 (.SR(FE_OFN1_n_logic0), 
	.O(data_o[15]), 
	.I(i_data_o[15]), 
	.E8(FE_OFN1_n_logic0), 
	.E4(FE_OFN1_n_logic0), 
	.E2(FE_OFN1_n_logic0), 
	.E(n_logic1));
endmodule

